<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StatenursingTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('statenursing')->delete();
        
        \DB::table('statenursing')->insert(array (
            0 => 
            array (
                'cnafees' => 'NA',
            'cnalink' => 'https://dph1.adph.state.al.us/NurseAideRegistry/(S(v343yoifoejr2lrydzh2cw32))/FAQ.aspx#anchor17',
                'cnanote' => 'No endorsement/reciprocity. Employer must get you on the registry.',
                'cnaperm' => 'NA',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 1,
                'lpnfees' => '$138.50',
                'lpnlink' => 'https://abn.alabama.gov/abnonline/ABNOnline_Endorsement.aspx',
                'lpnnote' => 'Temp lasts 90 days',
                'lpnperm' => '4-6 Weeks',
                'lpntemp' => '14 Days',
                'rnfees' => '$85',
                'rnlink' => 'https://www.abn.alabama.gov/',
                'rnnote' => 'null',
                'rnperm' => '1 Month',
                'rntemp' => '3-5 Days',
                'state' => 'Alabama',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'cnafees' => '$260-$330',
                'cnalink' => 'https://www.commerce.alaska.gov/web/portals/5/pub/nua4070.pdf',
                'cnanote' => 'Can work 120 without cert., but must have application in process',
                'cnaperm' => 'null',
                'cnatemp' => 'Can work 4 months not on registry 2 weeks',
                'created_at' => NULL,
                'id' => 2,
                'lpnfees' => '$375',
                'lpnlink' => 'https://www.commerce.alaska.gov/web/portals/5/pub/nur4014.pdf',
                'lpnnote' => 'Temp valid for 6 months',
                'lpnperm' => '6-8 Weeks',
                'lpntemp' => '10 Days',
                'rnfees' => '$375',
                'rnlink' => 'https://www.commerce.alaska.gov/web/portals/5/pub/nur4016.pdf',
                'rnnote' => 'null',
                'rnperm' => '4-6 Weeks',
                'rntemp' => '3-4 Weeks',
                'state' => 'Alaska',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'cnafees' => '$50',
                'cnalink' => 'https://azbn.boardsofnursing.org/azbn',
                'cnanote' => 'Online Application',
                'cnaperm' => '4-6 Months',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 3,
                'lpnfees' => '$50',
                'lpnlink' => 'https://www.azbn.gov/licensure-certification/application-instructions/rn-lpn-endorsement',
                'lpnnote' => 'null',
                'lpnperm' => '2-3 Months',
                'lpntemp' => '48+ hour walkthrough',
                'rnfees' => '$150',
                'rnlink' => 'http://www.azbn.gov/',
                'rnnote' => '2 days if contract in hand',
                'rnperm' => '4-8 Weeks',
                'rntemp' => '2-4 Weeks',
                'state' => 'Arizona',
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://view.officeapps.live.com/op/view.aspx?src=http%3A%2F%2Fhumanservices.arkansas.gov%2Fimages%2Fuploads%2Fdms%2Fdms_798.docx',
                'cnanote' => 'null',
                'cnaperm' => '2 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 4,
                'lpnfees' => '$125',
                'lpnlink' => 'https://www.arsbn.org/endorsement',
                'lpnnote' => 'Temp lasts 6 months',
                'lpnperm' => '10 Weeks',
                'lpntemp' => '3-4 Days',
                'rnfees' => '$100',
                'rnlink' => 'null',
                'rnnote' => 'null',
                'rnperm' => '1 AWeek',
                'rntemp' => '1 Week',
                'state' => 'Arkansas',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'cnafees' => 'NA',
                'cnalink' => 'https://www.cdph.ca.gov/CDPH%20Document%20Library/ControlledForms/cdph283b.pdf',
                'cnanote' => 'Fingerprint fee - must be done in CA',
                'cnaperm' => 'Varies',
                'cnatemp' => '4-8 Weeks',
                'created_at' => NULL,
                'id' => 5,
                'lpnfees' => '$200',
                'lpnlink' => 'http://www.bvnpt.ca.gov/applicants/application_for_vocational_nurse_licensure_by_endorsement.shtml',
                'lpnnote' => 'null',
                'lpnperm' => '6 Months',
                'lpntemp' => '6-10 Weeks',
                'rnfees' => '$400-$450',
                'rnlink' => 'https://www.rn.ca.gov/',
                'rnnote' => 'null',
                'rnperm' => '3-6 Months',
                'rntemp' => '3-4 Months',
                'state' => 'California',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'cnafees' => '$10',
                'cnalink' => 'https://apps.colorado.gov/dora/licensing/Default.aspx',
                'cnanote' => 'Online Application',
                'cnaperm' => '3-4 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 6,
                'lpnfees' => '$43',
                'lpnlink' => 'https://www.colorado.gov/pacific/dora/Nursing_LPN_Applications_Docs',
                'lpnnote' => 'null',
                'lpnperm' => '3-4 Weeks',
                'lpntemp' => '1-2 Weeks',
                'rnfees' => '$127',
                'rnlink' => '',
                'rnnote' => 'Receive Temp and Perm atthe same time',
                'rnperm' => '3-5 Weeks',
                'rntemp' => '3-5 Weeks',
                'state' => 'Colorado',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'cnafees' => '$55',
                'cnalink' => 'https://oap.prometric.com/CandidateWeb/Login/Login.aspx?ReturnUrl=%2fCandidateWeb%2fforms%2fCTNURS%2fConnecticutNurseAideRegistryApplication.aspx',
                'cnanote' => 'Online Application',
                'cnaperm' => '2 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 7,
                'lpnfees' => '$150',
                'lpnlink' => 'https://www.arsbn.org/endorsement',
                'lpnnote' => 'null',
                'lpnperm' => '10 Days',
                'lpntemp' => '5 Days',
                'rnfees' => '$180',
                'rnlink' => 'null',
            'rnnote' => '3-5 days for temporary (good for 120 days), signed agreement with NURSYS',
                'rnperm' => '7-10 Days',
                'rntemp' => '3-5 Days',
                'state' => 'Connecticut',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'cnafees' => '$30',
                'cnalink' => 'https://www.prometric.com/en-us/clients/nurseaide/documents/delaware/ReciprocityApplication.pdf',
                'cnanote' => 'Mail in forms',
                'cnaperm' => '2-3 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 8,
                'lpnfees' => '$150',
                'lpnlink' => 'https://dpr.delaware.gov/boards/nursing/forms/',
                'lpnnote' => 'null',
                'lpnperm' => '2 Weeks',
                'lpntemp' => '1 Week',
                'rnfees' => '$132',
                'rnlink' => 'https://dpr.delaware.gov/boards/nursing/forms/',
                'rnnote' => 'null',
                'rnperm' => '4-7 Weeks',
                'rntemp' => '1 Week',
                'state' => 'Delaware',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'cnafees' => '$15',
                'cnalink' => 'https://doh.dc.gov/sites/default/files/dc/sites/doh/publication/attachments/Nursing_Application_for_Nurse_Aide_Certification_by_Endorsement_-_PDF_Version.pdf',
                'cnanote' => 'null',
                'cnaperm' => 'NA',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 9,
                'lpnfees' => '$230',
                'lpnlink' => 'https://doh.dc.gov/sites/default/files/dc/sites/doh/publication/attachments/16%20RN-LPN%20Endorsement%20Application.pdf',
                'lpnnote' => 'Additional background check fee',
                'lpnperm' => 'NA',
                'lpntemp' => 'NA',
                'rnfees' => '$230',
                'rnlink' => 'https://dchealth.dc.gov/',
                'rnnote' => 'null',
                'rnperm' => '2-6 Weeks',
                'rntemp' => '2-4 Weeks',
                'state' => 'District Of Columbia',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'cnafees' => 'NA',
                'cnalink' => 'https://floridasnursing.gov/applications/cna-reciprocity-app.pdf',
                'cnanote' => 'Fingerprint Fees Varies',
                'cnaperm' => 'Up to 30 Days',
                'cnatemp' => 'Up to 3 Weeks',
                'created_at' => NULL,
                'id' => 10,
                'lpnfees' => '$110',
                'lpnlink' => 'https://floridasnursing.gov/licensing/licensed-practical-nurse-registered-nurse-by-endorsement/',
                'lpnnote' => 'Other fees may apply',
                'lpnperm' => '30 Days',
                'lpntemp' => 'NA',
                'rnfees' => '$100',
                'rnlink' => 'http://www.floridahealth.gov/licensing-and-regulation/index.html',
                'rnnote' => 'Level 2 background fingerprints required to get license',
                'rnperm' => '4-6 Weeks',
                'rntemp' => '4-6 Weeks',
                'state' => 'Florida',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://www.mmis.georgia.gov/portal/ResourceProxy.aspx?iCProxyTo=MS1BdHRhY2htZW50cy9Gb3Jtcy9SZWNpcHJvY2l0eSUyMEZvcm0ucGRm',
                'cnanote' => 'null',
                'cnaperm' => '2 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 11,
                'lpnfees' => '$75',
                'lpnlink' => 'http://sos.ga.gov/acrobat/PLB/13%20LPN%20Endorsement%20Application.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '10-15 Days',
                'lpntemp' => 'NA',
                'rnfees' => '$90',
                'rnlink' => 'http://sos.ga.gov/index.php/licensing/plb/45',
                'rnnote' => 'null',
                'rnperm' => '4 Weeks',
                'rntemp' => 'NA',
                'state' => 'Georgia',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'cnafees' => '$25',
                'cnalink' => 'https://www.prometric.com/en-us/clients/nurseaide/documents/hawaii/HI_CNA_APP.pdf',
                'cnanote' => 'Mail in forms',
                'cnaperm' => '2-3 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 12,
                'lpnfees' => '$146-$202',
                'lpnlink' => 'http://cca.hawaii.gov/pvl/boards/nursing/application_publications/',
                'lpnnote' => 'null',
                'lpnperm' => '10-15 Days',
                'lpntemp' => '10-15 Days',
                'rnfees' => '$202 or $146',
                'rnlink' => 'http://cca.hawaii.gov/pvl/boards/nursing/application_publications/',
                'rnnote' => 'Endorsement fee depends on even or odd year',
                'rnperm' => '2 Weeks',
                'rntemp' => '24 Hours',
                'state' => 'Hawaii',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'http://healthandwelfare.idaho.gov/Portals/0/Medical/LicensingCertification/CNAOutOfStateTransferForm.pdf',
                'cnanote' => 'null',
                'cnaperm' => '1 Month',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 13,
                'lpnfees' => '$110',
                'lpnlink' => 'https://ibn.idaho.gov/IBNPortal/BoardAdditional.aspx?Board=IBON&BureauLinkID=100',
                'lpnnote' => 'null',
                'lpnperm' => '6-8 Weeks',
                'lpntemp' => 'NA',
                'rnfees' => '$152',
                'rnlink' => 'https://ibn.idaho.gov/IBNPortal/BoardAdditional.aspx?Board=IBON&BureauLinkID=100',
                'rnnote' => 'null',
                'rnperm' => '2-4 Weeks',
                'rntemp' => '24 Hours',
                'state' => 'Idaho',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'cnafees' => '$25',
                'cnalink' => 'https://nurseaidetesting.com/out-of-state-cna-application/',
                'cnanote' => 'null',
                'cnaperm' => '1-3 Days',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 14,
                'lpnfees' => '$75',
                'lpnlink' => 'https://www.nursinglicensure.org/state/nursing-license-illinois.html#lpn',
                'lpnnote' => 'null',
                'lpnperm' => '2-4 Weeks',
                'lpntemp' => '3-4 Weeks',
                'rnfees' => '$50',
                'rnlink' => 'https://www.nursinglicensure.org/state/nursing-license-illinois.html#rn',
                'rnnote' => 'null',
                'rnperm' => '4-6 Weeks',
                'rntemp' => '2-4 Weeks',
                'state' => 'illinois',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'cnafees' => '$65',
                'cnalink' => 'https://www.ivytech.edu/cna/4368.html',
                'cnanote' => 'Mail in forms',
                'cnaperm' => '4-12 Weeks',
                'cnatemp' => '2-6 Weeks',
                'created_at' => NULL,
                'id' => 15,
                'lpnfees' => '$60',
                'lpnlink' => 'https://www.in.gov/pla/2506.htm',
                'lpnnote' => 'null',
                'lpnperm' => '4-5 Weeks',
                'lpntemp' => '10-14 Days',
                'rnfees' => '$50',
                'rnlink' => 'https://www.in.gov/pla/nursing.htm',
                'rnnote' => 'null',
                'rnperm' => '2-5 Weeks',
                'rntemp' => '1-2 Weeks',
                'state' => 'Indiana',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://dia.iowa.gov/sites/default/files/documents/2016/01/dcw_application.pdf',
                'cnanote' => 'null',
                'cnaperm' => '1-2 Weeks',
                'cnatemp' => '3-5 Days',
                'created_at' => NULL,
                'id' => 16,
                'lpnfees' => '$169',
                'lpnlink' => 'https://nursing.iowa.gov/licensure/endorsement-licensure-another-state',
                'lpnnote' => 'null',
                'lpnperm' => '5-10 Days',
                'lpntemp' => '5-10 Days',
                'rnfees' => '$169',
                'rnlink' => 'https://nursing.iowa.gov/licensure/endorsement-licensure-another-state',
                'rnnote' => 'null',
                'rnperm' => '1-2 Weeks',
                'rntemp' => '1 Week',
                'state' => 'Iowa',
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'cnafees' => '$2-',
            'cnalink' => 'https://www.kdads.ks.gov/docs/default-source/survey-certification-and-credentialing-commission/Health-Occupations-Credentialing/certificattion-(cna-hha-cma)/certification-verification/forms/interstate-application-form.pdf',
                'cnanote' => 'Must pass exam with 75%',
                'cnaperm' => 'Exam / 3-4 Weeks after',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 17,
                'lpnfees' => '$50',
                'lpnlink' => 'https://ksbn.kansas.gov/wp-content/uploads/Forms/Endorsement.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '4-6 Weeks',
                'lpntemp' => '1 Week',
                'rnfees' => '$125',
                'rnlink' => 'https://ksbn.kansas.gov/',
                'rnnote' => 'null',
                'rnperm' => '30 Days',
                'rntemp' => '7-10 Days',
                'state' => 'Kansas',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://kbn.ky.gov/knar/Pages/reciprocity.aspx',
                'cnanote' => 'null',
                'cnaperm' => '1-2 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 18,
                'lpnfees' => '$179.75',
                'lpnlink' => 'https://kbn.ky.gov/apply/Pages/Endorsement/endorsement.aspx',
                'lpnnote' => 'null',
                'lpnperm' => '4-6 Weeks',
                'lpntemp' => '10-14 Days',
                'rnfees' => '$330',
                'rnlink' => 'https://kbn.ky.gov/Pages/default.aspx',
                'rnnote' => 'null',
                'rnperm' => '5-10 Weeks',
                'rntemp' => 'NA',
                'state' => 'Kentucky',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'cnafees' => '$35',
                'cnalink' => 'http://ldh.la.gov/assets/medicaid/hss/NurseAide/NurseAideTrainingReciprocityForm.pdf',
                'cnanote' => 'Mail in forms',
                'cnaperm' => 'NA',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 19,
                'lpnfees' => '$175.75',
                'lpnlink' => 'http://www.lsbpne.com/requirements_for_endorsement.phtml',
                'lpnnote' => 'Temp last 12 weeks',
                'lpnperm' => '12 Weeks',
                'lpntemp' => 'Walkthrough',
                'rnfees' => '$140',
                'rnlink' => 'http://www.lsbn.state.la.us/',
                'rnnote' => 'Walkthrough with clean background. Temp cost and additional $100',
                'rnperm' => '4-6 Weeks',
                'rntemp' => '24 Hours',
                'state' => 'Louisiana',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'cnafees' => '$20',
                'cnalink' => 'https://www.maine.gov/dhhs/dlc/cna/',
                'cnanote' => 'null',
                'cnaperm' => '4-6 Months',
                'cnatemp' => 'Can work 4 months not on registry 2 weeks',
                'created_at' => NULL,
                'id' => 20,
                'lpnfees' => '$50',
                'lpnlink' => 'http://www.maine.gov/boardofnursing/docs/LPN-Endorsement-App-10-24-16.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '1 Week',
                'lpntemp' => '7-14 Days',
                'rnfees' => '$75',
                'rnlink' => 'https://www.maine.gov/boardofnursing/',
                'rnnote' => 'null',
                'rnperm' => '2-4 Weeks',
                'rntemp' => '7-10 Days',
                'state' => 'Maine',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'cnafees' => '$20',
                'cnalink' => 'http://www.mbon.org/Documents/cna-endorsementinfo.pdf',
                'cnanote' => 'Additional fingerprint fees',
                'cnaperm' => 'Up to 3 Months',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 21,
                'lpnfees' => '$100',
                'lpnlink' => 'https://mbon.maryland.gov/Pages/licensure-by-endorsement.aspx',
                'lpnnote' => 'null',
                'lpnperm' => '4-6 Weeks',
                'lpntemp' => 'Walkthrough',
                'rnfees' => '$100',
                'rnlink' => 'http://www.mbon.org/Pages/default.aspx',
                'rnnote' => 'Can go inside state line to expedite fingerprints',
                'rnperm' => '3-4 Weeks',
                'rntemp' => '1-2 Weeks',
                'state' => 'Maryland',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://www.redcross.org/content/dam/redcross/atg/Northeast_Media/Eastern_Mass/Eastern_MA_-_NAT_-_NAT_Reciprocity.pdf',
                'cnanote' => 'null',
                'cnaperm' => '3 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 22,
                'lpnfees' => '$275',
                'lpnlink' => 'https://www.pcshq.com/?page=health,ulicensedpracticalnurseslpnu',
                'lpnnote' => 'null',
                'lpnperm' => '4 Weeks',
                'lpntemp' => 'NA',
                'rnfees' => '$275',
                'rnlink' => 'https://www.mass.gov/orgs/board-of-registration-in-nursing',
                'rnnote' => 'null',
                'rnperm' => '2-4 Weeks',
                'rntemp' => 'NA',
                'state' => 'Massachusetts',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'cnafees' => 'Fees Vary',
                'cnalink' => 'https://www.prometric.com/en-us/clients/nurseaide/pages/mi.aspx',
                'cnanote' => 'Certain states require training program',
                'cnaperm' => 'Exam / 2 Weeks after',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 23,
                'lpnfees' => '$54',
                'lpnlink' => 'https://www.nursinglicensure.org/state/nursing-license-michigan.html#lpn',
                'lpnnote' => 'null',
                'lpnperm' => '6-8 Weeks',
                'lpntemp' => 'NA',
                'rnfees' => '$64',
                'rnlink' => 'https://www.michigan.gov/healthlicense',
                'rnnote' => 'null',
                'rnperm' => '4 Weeks',
                'rntemp' => '4 Weeks',
                'state' => 'Michigan',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://www.health.state.mn.us/facilities/providers/nursingassistant/docs/interstate.pdf',
                'cnanote' => 'Must mail in',
                'cnaperm' => '2-4 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 24,
                'lpnfees' => '$115',
                'lpnlink' => 'https://mn.gov/boards/nursing/licensure/apply-for-a-license/apply-by-endorsement.jsp',
                'lpnnote' => 'Temp lasts 60 days',
                'lpnperm' => 'Varies',
                'lpntemp' => '1-5 Days',
                'rnfees' => '$105',
                'rnlink' => 'https://mn.gov/boards/nursing/',
                'rnnote' => 'null',
                'rnperm' => '4-6 Weeks',
                'rntemp' => '2-3 Weeks',
                'state' => 'Minnesota',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'cnafees' => '$26',
                'cnalink' => 'https://www.asisvcs.com/publications/pdf/072503.pdf',
            'cnanote' => 'Must have verification of paid employment within last 24 months (ex: pay stub, w2, etc)',
                'cnaperm' => '2-4 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 25,
                'lpnfees' => 'NA',
                'lpnlink' => 'https://gateway.licensure.msbn.ms.gov/',
                'lpnnote' => 'null',
                'lpnperm' => '2-3 Weeks',
                'lpntemp' => '5 Days',
                'rnfees' => '$100',
                'rnlink' => 'https://www.msbn.ms.gov/',
                'rnnote' => 'null',
                'rnperm' => '7-10 Days',
                'rntemp' => '5 Days',
                'state' => 'Mississippi',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'cnafees' => 'Fees Vary',
                'cnalink' => 'http://health.mo.gov/safety/cnaregistry/cna.php#challenge',
                'cnanote' => 'null',
                'cnaperm' => 'Exam / 2-3 Weeks after',
                'cnatemp' => '2-3 Weeks',
                'created_at' => NULL,
                'id' => 26,
                'lpnfees' => '$95.80',
                'lpnlink' => 'https://pr.mo.gov/boards/nursing/375-0222.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '2-3 Weeks',
                'lpntemp' => 'Walkthrough',
                'rnfees' => '$55',
                'rnlink' => 'https://www.pr.mo.gov/Default.asp',
                'rnnote' => 'null',
                'rnperm' => '3-4 Weeks',
                'rntemp' => '24 Hours',
                'state' => 'Missouri',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://cna.hhs.mt.gov/datamart/ePass.do',
                'cnanote' => 'null',
                'cnaperm' => '1-2 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 27,
                'lpnfees' => '$227.25',
                'lpnlink' => 'http://b.bsd.dli.mt.gov/license/bsd_boards/nur_board/pdf/nur_end_app.pdf',
                'lpnnote' => 'Fingerprint and Background Fees',
                'lpnperm' => '10 Days',
                'lpntemp' => '4-6 Weeks',
                'rnfees' => '$200',
                'rnlink' => 'http://bsd.dli.mt.gov/license',
                'rnnote' => 'Must verify all licenses held temp or expired',
                'rnperm' => '3-6 Weeks',
                'rntemp' => '2-3 Weeks',
                'state' => 'Montana',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'cnafees' => '$20 course',
                'cnalink' => 'http://dhhs.ne.gov/licensure/Pages/Certification-and-Verification.aspx',
                'cnanote' => 'null',
                'cnaperm' => '2-4 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 28,
                'lpnfees' => '$59.50 - $151.75',
                'lpnlink' => 'http://dhhs.ne.gov/publichealth/Licensure/Documents/EndorsementRNLPN.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '2-8 Weeks',
                'lpntemp' => '3-6 Weeks',
                'rnfees' => '$125',
                'rnlink' => 'http://dhhs.ne.gov/publichealth/pages/crlNursingAppsReqsFeesLPNRN.aspx',
                'rnnote' => 'null',
                'rnperm' => '8 Weeks',
                'rntemp' => '3 Weeks',
                'state' => 'Nebraska',
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'cnafees' => '$101',
                'cnalink' => 'https://nevadanursingboard.org/',
                'cnanote' => 'Fingerprinting Fee',
                'cnaperm' => '2-4 Months',
                'cnatemp' => '1 Week',
                'created_at' => NULL,
                'id' => 29,
                'lpnfees' => '$145',
                'lpnlink' => 'https://nevadanursingboard.org/',
                'lpnnote' => 'null',
                'lpnperm' => 'NA',
                'lpntemp' => '1 Week',
                'rnfees' => '$105',
                'rnlink' => 'https://nevadanursingboard.org/licensure-and-certification/',
                'rnnote' => 'null',
                'rnperm' => '4-5 Weeks',
                'rntemp' => '1-5 Days',
                'state' => 'Nevada',
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'cnafees' => '$82',
                'cnalink' => 'https://www.oplc.nh.gov/nursing/documents/lna-endorsement.pdf',
                'cnanote' => 'Fingerprinting Fee',
                'cnaperm' => '4-6 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 30,
                'lpnfees' => '$167',
                'lpnlink' => 'https://www.oplc.nh.gov/nursing/documents/endorsement-licensing-powerpoint.pdf',
                'lpnnote' => 'Temp valid for 120 days',
                'lpnperm' => '8 Weeks',
                'lpntemp' => '8 Weeks',
                'rnfees' => '$120',
                'rnlink' => 'https://www.nh.gov/nursing/',
                'rnnote' => 'null',
                'rnperm' => '6-9 Weeks',
                'rntemp' => '6-9 Weeks',
                'state' => 'New Hampshire',
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'cnafees' => '$30',
                'cnalink' => 'null',
                'cnanote' => 'Some states do not transfer, Call 1-877-774-4243',
                'cnaperm' => '4-6  Weeks',
                'cnatemp' => '120 Days',
                'created_at' => NULL,
                'id' => 31,
                'lpnfees' => '$261.44',
                'lpnlink' => 'https://www.njconsumeraffairs.gov/nur/Pages/applications.aspx',
                'lpnnote' => 'null',
                'lpnperm' => '4-6 Weeks',
                'lpntemp' => 'NA',
                'rnfees' => '$200',
                'rnlink' => 'https://www.njconsumeraffairs.gov/',
                'rnnote' => 'null',
                'rnperm' => '2-4 Months',
                'rntemp' => 'NA',
                'state' => 'New Jersey',
                'updated_at' => NULL,
            ),
            31 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'null',
                'cnanote' => 'Current CNA certification, Social Security Card, Driver License and Mailing Address to ATTN Nurse Aide Registry PO Box 26110 Santa',
                'cnaperm' => '3-4 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 32,
                'lpnfees' => '$115',
                'lpnlink' => 'http://nmbon.sks.com/licensure-endorsement.aspx',
                'lpnnote' => 'null',
                'lpnperm' => '2 Weeks',
                'lpntemp' => '2 Weeks',
                'rnfees' => '$110',
                'rnlink' => 'http://nmbon.sks.com/',
                'rnnote' => 'null',
                'rnperm' => '4-6 Weeks',
                'rntemp' => 'NA',
                'state' => 'New Mexico',
                'updated_at' => NULL,
            ),
            32 => 
            array (
                'cnafees' => '$50',
                'cnalink' => 'https://www.prometric.com/en-us/clients/nurseaide/documents/new-york/ny_na_registryapp.pdf',
                'cnanote' => 'null',
                'cnaperm' => '1-2 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 33,
                'lpnfees' => '$178',
                'lpnlink' => 'http://www.op.nysed.gov/prof/nurse/nurseforms.htm',
                'lpnnote' => 'null',
                'lpnperm' => '6-8 Weeks',
                'lpntemp' => 'NA',
                'rnfees' => '$143',
                'rnlink' => 'http://www.op.nysed.gov/prof/nurse/article139.htm',
                'rnnote' => 'null',
                'rnperm' => '6-8 Weeks',
                'rntemp' => 'NA',
                'state' => 'New York',
                'updated_at' => NULL,
            ),
            33 => 
            array (
                'cnafees' => '$101',
                'cnalink' => 'https://www.ncnar.org/index1.jsp',
                'cnanote' => 'No reciprocity/endorsement or transfer from other states. Must pass exam',
                'cnaperm' => 'Exam / 4-6 Weeks After',
                'cnatemp' => '4-6 Weeks',
                'created_at' => NULL,
                'id' => 34,
                'lpnfees' => '$150',
                'lpnlink' => 'https://www.ncbon.com/licensure-listing-apply-licensure-by-endorsement-licensure-by-endorsement',
                'lpnnote' => 'null',
                'lpnperm' => '6-8 Weeks',
                'lpntemp' => '2-3 Days',
                'rnfees' => '$150',
                'rnlink' => 'https://www.ncbon.com/',
                'rnnote' => 'The Board processes licenses on Tuesday and Wednesday. If they submit on one of these days, they will receive license by Saturday-if they have a clean background',
                'rnperm' => '6 Weeks',
                'rntemp' => '8 Days',
                'state' => 'North Carolina',
                'updated_at' => NULL,
            ),
            34 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://services.ndnar.org/lic/cna/apply/',
                'cnanote' => 'null',
                'cnaperm' => '2-4 Weeks',
                'cnatemp' => '10 Days',
                'created_at' => NULL,
                'id' => 35,
                'lpnfees' => '$160',
                'lpnlink' => 'https://www.ndbon.org/NurseLicensure/InitialEndorse/index.asp',
                'lpnnote' => 'null',
                'lpnperm' => '2 Weeks',
                'lpntemp' => '1 Week',
                'rnfees' => '$160',
                'rnlink' => 'https://www.ndbon.org/',
                'rnnote' => 'null',
                'rnperm' => '3 Days',
                'rntemp' => '3 Days',
                'state' => 'North Dakota',
                'updated_at' => NULL,
            ),
            35 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'http://www.nursing.ohio.gov/forms.htm#ExamEndorseForms',
                'cnanote' => 'Contact the OH Department of Health. Contact Number: 800-582-5908 or 614-752-9500',
                'cnaperm' => '1-2 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 36,
                'lpnfees' => '$75',
                'lpnlink' => 'http://www.nursing.ohio.gov/PDFS/Education/Category_A_Law_Rules.pdf, http://www.nursing.ohio.gov/forms.htm#ExamEndorseForms',
                'lpnnote' => 'Must complete 2 hours of continuing education',
                'lpnperm' => 'NA',
                'lpntemp' => 'NA',
                'rnfees' => '$75',
                'rnlink' => 'http://www.nursing.ohio.gov/',
                'rnnote' => 'null',
                'rnperm' => '4-6 Weeks',
                'rntemp' => 'NA',
                'state' => 'Ohio',
                'updated_at' => NULL,
            ),
            36 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://www.ok.gov/health2/documents/Reciprocity_Application_ODH-735_10-11-2016_vlk_&_%20Affidavit_ODH_301-FILLABLE.pdf',
                'cnanote' => 'Main in forms',
                'cnaperm' => '1-2 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 37,
                'lpnfees' => '$95',
                'lpnlink' => 'http://nursing.ok.gov/endorseused07.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '2 Weeks',
                'lpntemp' => '2 Weeks',
                'rnfees' => '$85',
                'rnlink' => 'http://nursing.ok.gov/',
                'rnnote' => 'Timeframe is with a CLEAN background',
                'rnperm' => '4-6 Weeks',
                'rntemp' => '3-4 Weeks',
                'state' => 'Oklahoma',
                'updated_at' => NULL,
            ),
            37 => 
            array (
                'cnafees' => '$60',
                'cnalink' => 'https://osbn.oregon.gov/OBNPortal/DesktopDefault.aspx?tabindex=0&tabid=5&utyp=4',
                'cnanote' => 'Fingerprinting Fee $52',
                'cnaperm' => '4-6 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 38,
                'lpnfees' => '$268.50',
                'lpnlink' => 'https://www.oregon.gov/osbn/pages/rn-lpnlicensure.aspx#RN/LPN_Endorsement_into_Oregon',
                'lpnnote' => 'Home states verification fee',
                'lpnperm' => '3-4 Weeks',
                'lpntemp' => 'NA',
                'rnfees' => '$245',
                'rnlink' => 'https://www.oregon.gov/OSBN/pages/index.aspx',
                'rnnote' => 'null',
                'rnperm' => '3-4 Weeks',
                'rntemp' => 'NA',
                'state' => 'Oregon',
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'http://www.pearsonvue.com/pa/nurseaides/',
                'cnanote' => 'Online Application',
                'cnaperm' => '2-4 Weeks',
                'cnatemp' => 'Work up to 120 days',
                'created_at' => NULL,
                'id' => 39,
                'lpnfees' => '$155',
                'lpnlink' => 'https://www.dos.pa.gov/ProfessionalLicensing/BoardsCommissions/Nursing/Documents/Applications%20and%20Forms/Online%20Endorsement%20Combined%20Instructions.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '6-8 Weeks',
                'lpntemp' => '7-10 Days',
                'rnfees' => '$100',
                'rnlink' => 'https://www.dos.pa.gov/ProfessionalLicensing/Pages/default.aspx',
                'rnnote' => 'null',
                'rnperm' => '6 Weeks',
                'rntemp' => '3-6 Weeks',
                'state' => 'Pennsylvania',
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'cnafees' => '$35',
                'cnalink' => 'http://health.ri.gov/applications/NursingAssistant.pdf',
                'cnanote' => 'Mail in only',
                'cnaperm' => '8 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 40,
                'lpnfees' => 'NA',
                'lpnlink' => 'https://healthri.mylicense.com/',
                'lpnnote' => 'null',
                'lpnperm' => '8 Weels',
                'lpntemp' => 'NA',
                'rnfees' => '$135',
                'rnlink' => 'http://www.health.ri.gov/licenses/detail.php?id=231/',
                'rnnote' => 'null',
                'rnperm' => '8-10 Weeks',
                'rntemp' => '6-8 Weeks',
                'state' => 'Rhode Island',
                'updated_at' => NULL,
            ),
            40 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://www.asisvcs.com/publications/pdf/074102.pdf',
                'cnanote' => 'Online Application',
                'cnaperm' => 'Exam / 7-10 Days',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 41,
                'lpnfees' => '$110',
                'lpnlink' => 'https://www.llr.sc.gov/POL/Nursing/pdf/RN_LPN_Endorsement.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '6-8 Weeks',
                'lpntemp' => 'NA',
                'rnfees' => '$100',
                'rnlink' => 'https://www.llr.sc.gov/pol/nursing/',
                'rnnote' => 'null',
                'rnperm' => '2 Weeks',
                'rntemp' => '24 Hours',
                'state' => 'South Carolina',
                'updated_at' => NULL,
            ),
            41 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://www.sduap.org/CNA/apply/endorse/index.asp',
                'cnanote' => 'null',
                'cnaperm' => '1-2 Weeks',
                'cnatemp' => 'Work up to 120 days',
                'created_at' => NULL,
                'id' => 42,
                'lpnfees' => '$100',
                'lpnlink' => 'https://www.sdbon.org/rn_lpn/endorse/',
                'lpnnote' => 'Temp is good for 90 days',
                'lpnperm' => 'null',
                'lpntemp' => '3-6 Weeks',
                'rnfees' => '$100',
                'rnlink' => 'http://doh.sd.gov/boards/nursing/',
                'rnnote' => 'null',
                'rnperm' => '3-6 Weeks',
                'rntemp' => '24 Hours',
                'state' => 'South Dakota',
                'updated_at' => NULL,
            ),
            42 => 
            array (
                'cnafees' => '$20',
                'cnalink' => 'https://www.pdffiller.com/en/link_to_fill/261126472.htm',
                'cnanote' => 'Mail in only',
                'cnaperm' => '5-7 Days',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 43,
                'lpnfees' => '$115',
                'lpnlink' => 'https://www.tn.gov/content/dam/tn/health/documents/Nursing_Tutorial_for_Endorsement_RN-LPN.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '6-8 Weeks',
                'lpntemp' => '4-6 Weeks',
                'rnfees' => '$115',
                'rnlink' => 'https://www.tn.gov/health',
                'rnnote' => 'null',
                'rnperm' => '4-6 Weeks',
                'rntemp' => 'NA',
                'state' => 'Tennessee',
                'updated_at' => NULL,
            ),
            43 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://hhs.texas.gov/doing-business-hhs/licensing-credentialing-regulation/credentialing/nurse-aide-registry/nar-forms',
                'cnanote' => 'Fingerprinting Fee',
                'cnaperm' => '10 Days',
                'cnatemp' => '6-8 Weeks',
                'created_at' => NULL,
                'id' => 44,
                'lpnfees' => '$111',
                'lpnlink' => 'https://www.bon.texas.gov/licensure_endorsement.asp#online',
                'lpnnote' => 'null',
                'lpnperm' => '10 Days',
                'lpntemp' => '10 Days',
                'rnfees' => 'null',
                'rnlink' => 'http://www.bne.state.tx.us/',
                'rnnote' => 'null',
                'rnperm' => 'null',
                'rntemp' => 'null',
                'state' => 'Texas',
                'updated_at' => NULL,
            ),
            44 => 
            array (
                'cnafees' => '$40',
                'cnalink' => 'http://www.utahcna.com/docs/Reciprocity%20Application.pdf',
                'cnanote' => 'null',
                'cnaperm' => '1-2 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 45,
                'lpnfees' => '$100',
                'lpnlink' => 'https://dopl.utah.gov/licensing/forms/applications/012_RN_LPN.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '2-3 Weeks',
                'lpntemp' => 'NA',
                'rnfees' => '$100',
                'rnlink' => 'https://dopl.utah.gov/nurse/index.html',
                'rnnote' => 'null',
                'rnperm' => '10-15 Days',
                'rntemp' => 'NA',
                'state' => 'Utah',
                'updated_at' => NULL,
            ),
            45 => 
            array (
                'cnafees' => '$20',
                'cnalink' => 'https://cms.sec.state.vt.us:8443/share/s/zSZ87t1_TT2gMVhi5bbYEg',
                'cnanote' => 'null',
                'cnaperm' => '1-3 Weeks',
                'cnatemp' => '2-5 Days',
                'created_at' => NULL,
                'id' => 46,
                'lpnfees' => '$150',
                'lpnlink' => 'https://www.sec.state.vt.us/professional-regulation/online-licensing.aspx',
                'lpnnote' => 'null',
                'lpnperm' => '3-6 Days',
                'lpntemp' => 'Walkthrough',
                'rnfees' => '$150',
                'rnlink' => 'https://www.sec.state.vt.us/professional-regulation/list-of-professions/nursing.aspx',
                'rnnote' => 'null',
                'rnperm' => '3-5 Days',
                'rntemp' => 'NA',
                'state' => 'Vermont',
                'updated_at' => NULL,
            ),
            46 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://www.license.dhp.virginia.gov/apply/',
                'cnanote' => 'Apps must be sent to the board',
                'cnaperm' => '1-3 Months',
                'cnatemp' => '1-3 Months',
                'created_at' => NULL,
                'id' => 47,
                'lpnfees' => '$170',
                'lpnlink' => 'https://www.dhp.virginia.gov/nursing/nursing_forms.htm#LPN',
                'lpnnote' => 'null',
                'lpnperm' => '2-6 Weeks',
                'lpntemp' => '3-5 Days',
                'rnfees' => '$190',
                'rnlink' => 'https://www.dhp.virginia.gov/nursing/',
                'rnnote' => 'null',
                'rnperm' => '45 Days',
                'rntemp' => 'NA',
                'state' => 'Virginia',
                'updated_at' => NULL,
            ),
            47 => 
            array (
                'cnafees' => '$97',
                'cnalink' => 'https://www.doh.wa.gov/portals/1/Documents/Pubs/667039.pdf',
                'cnanote' => 'Fingerprinting Fee',
                'cnaperm' => 'Up to 3 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 48,
                'lpnfees' => '$88',
                'lpnlink' => 'https://www.doh.wa.gov/portals/1/Documents/Pubs/669224.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '4-6 Weeks',
                'lpntemp' => 'NA',
                'rnfees' => '$120',
                'rnlink' => 'https://www.doh.wa.gov/',
                'rnnote' => 'null',
                'rnperm' => '4-6 Weeks',
                'rntemp' => '3-4 Weeks',
                'state' => 'Washington',
                'updated_at' => NULL,
            ),
            48 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://ohflac.wvdhhr.org/Apps/Forms/NAReciprocity',
                'cnanote' => 'Mail in only',
                'cnaperm' => '1-2 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 49,
                'lpnfees' => '$51-$81',
                'lpnlink' => 'https://wvpn.boardsofnursing.org/wvpn',
                'lpnnote' => 'Renew every Oct 31',
                'lpnperm' => '7-10 Days',
                'lpntemp' => '5-7 Days',
                'rnfees' => '$100',
                'rnlink' => 'http://wvrnboard.wv.gov/Pages/default.aspx',
                'rnnote' => '5-7 days for temp if SPOTLESS background. Must apply for Temp and Perm at the same time for $125',
                'rnperm' => '3-4 Weeks',
                'rntemp' => '5-7 Days',
                'state' => 'West Virginia',
                'updated_at' => NULL,
            ),
            49 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'http://hdmaster.com/testing/cnatesting/wisconsin/WIformpages/WIforms/9110WI.pdf?_sm_au_=iDVvnVZ84HVkJJtH',
                'cnanote' => 'Mail in only',
                'cnaperm' => '2-3 Weeks',
                'cnatemp' => '2-3 Weeks',
                'created_at' => NULL,
                'id' => 50,
                'lpnfees' => '$92',
                'lpnlink' => 'https://dsps.wi.gov/Credentialing/Health/fm3087.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '5-6 Weeks',
                'lpntemp' => '5-6 Weeks',
                'rnfees' => '$82',
                'rnlink' => 'https://dsps.wi.gov/pages/Professions/RN/Default.aspx',
                'rnnote' => 'null',
                'rnperm' => '3-6 Weeks',
                'rntemp' => 'NA',
                'state' => 'Wisconsin',
                'updated_at' => NULL,
            ),
            50 => 
            array (
                'cnafees' => '$150',
                'cnalink' => 'http://nursing.state.wy.us/',
                'cnanote' => 'Fingerprinting Fee, Online Application',
                'cnaperm' => '2-4 Months',
                'cnatemp' => 'Up to 3 Weeks',
                'created_at' => NULL,
                'id' => 51,
                'lpnfees' => '$185',
                'lpnlink' => 'https://nursing-online.state.wy.us/Resources/LPN%20Endorsement%20App%204-22-2013.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '2 Weeks',
                'lpntemp' => '7-10 Days',
                'rnfees' => '$135',
                'rnlink' => 'http://nursing.state.wy.us/',
                'rnnote' => 'null',
                'rnperm' => '4-8 Weeks',
                'rntemp' => '2-5 Days',
                'state' => 'Wyoming',
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}