<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StatenursingTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('statenursing')->delete();

        \DB::table('statenursing')->insert(array (
            0 =>
            array (
                'id' => 1,
                'state' => 'Alabama',
                'rntemp' => '3-5 Days',
                'rnperm' => '1 Month',
                'rnfees' => '$85',
                'rnnote' => 'null',
                'rnlink' => 'https://www.abn.alabama.gov/',
                'lpntemp' => '14 Days',
                'lpnperm' => '4-6 Weeks',
                'lpnfees' => '$138.50',
                'lpnnote' => 'Temp lasts 90 days',
                'lpnlink' => 'https://www.abn.alabama.gov/',
                'cnatemp' => 'NA',
                'cnaperm' => 'NA',
                'cnafees' => 'NA',
                'cnanote' => 'No endorsement/reciprocity. Employer must get you on the registry.',
                'cnalink' => 'https://www.cnalicense.org/by-state/alabama/',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'state' => 'Alaska',
                'rntemp' => '3-4 Weeks',
                'rnperm' => '4-6 Weeks',
                'rnfees' => '$375',
                'rnnote' => 'null',
                'rnlink' => 'https://www.commerce.alaska.gov/web/portals/5/pub/nur4016.pdf',
                'lpntemp' => '10 Days',
                'lpnperm' => '6-8 Weeks',
                'lpnfees' => '$375',
                'lpnnote' => 'Temp valid for 6 months',
                'lpnlink' => 'https://www.commerce.alaska.gov/web/portals/5/pub/nur4014.pdf',
                'cnatemp' => 'Can work 4 months not on registry 2 weeks',
                'cnaperm' => 'null',
                'cnafees' => '$260-$330',
                'cnanote' => 'Can work 120 without cert., but must have application in process',
                'cnalink' => 'https://www.commerce.alaska.gov/web/cbpl/ProfessionalLicensing/NurseAideRegistry.aspx',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'state' => 'Arizona',
                'rntemp' => '2-4 Weeks',
                'rnperm' => '4-8 Weeks',
                'rnfees' => '$150',
                'rnnote' => '2 days if contract in hand',
                'rnlink' => 'https://www.azbn.gov/licenses-certifications/apply-for-a-license',
                'lpntemp' => '48+ hour walkthrough',
                'lpnperm' => '2-3 Months',
                'lpnfees' => '$50',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.azbn.gov/licenses-certifications/apply-for-a-license',
                'cnatemp' => 'NA',
                'cnaperm' => '4-6 Months',
                'cnafees' => '$50',
                'cnanote' => 'Online Application',
                'cnalink' => 'https://www.azbn.gov/licenses-certifications/apply-for-a-license',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'state' => 'Arkansas',
                'rntemp' => '1 Week',
                'rnperm' => '1 AWeek',
                'rnfees' => '$100',
                'rnnote' => 'null',
                'rnlink' => 'https://healthy.arkansas.gov/programs-services/topics/arkansas-board-of-nursing/',
                'lpntemp' => '3-4 Days',
                'lpnperm' => '10 Weeks',
                'lpnfees' => '$125',
                'lpnnote' => 'Temp lasts 6 months',
                'lpnlink' => 'https://healthy.arkansas.gov/programs-services/topics/arkansas-board-of-nursing/',
                'cnatemp' => 'NA',
                'cnaperm' => '2 Weeks',
                'cnafees' => 'FREE',
                'cnanote' => 'null',
                'cnalink' => 'https://humanservices.arkansas.gov/divisions-shared-services/provider-services-quality-assurance/occupational-licensing/cna-nha-training-program/',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'state' => 'California',
                'rntemp' => '3-4 Months',
                'rnperm' => '3-6 Months',
                'rnfees' => '$400-$450',
                'rnnote' => 'null',
                'rnlink' => 'https://www.rn.ca.gov/applicants/index.shtml',
                'lpntemp' => '6-10 Weeks',
                'lpnperm' => '6 Months',
                'lpnfees' => '$200',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.rn.ca.gov/applicants/index.shtml',
                'cnatemp' => '4-8 Weeks',
                'cnaperm' => 'Varies',
                'cnafees' => 'NA',
                'cnanote' => 'Fingerprint fee - must be done in CA',
                'cnalink' => 'https://www.cdph.ca.gov/Programs/CHCQ/LCP/Pages/CNA.aspx',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'state' => 'Colorado',
                'rntemp' => '3-5 Weeks',
                'rnperm' => '3-5 Weeks',
                'rnfees' => '$127',
                'rnnote' => 'Receive Temp and Perm atthe same time',
                'rnlink' => 'https://dpo.colorado.gov/Nursing/Applications',
                'lpntemp' => '1-2 Weeks',
                'lpnperm' => '3-4 Weeks',
                'lpnfees' => '$43',
                'lpnnote' => 'null',
                'lpnlink' => 'https://dpo.colorado.gov/Nursing/Applications',
                'cnatemp' => 'NA',
                'cnaperm' => '3-4 Weeks',
                'cnafees' => '$10',
                'cnanote' => 'Online Application',
                'cnalink' => 'https://dpo.colorado.gov/Nursing/CNAApplications',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'state' => 'Connecticut',
                'rntemp' => '3-5 Days',
                'rnperm' => '7-10 Days',
                'rnfees' => '$180',
            'rnnote' => '3-5 days for temporary (good for 120 days), signed agreement with NURSYS',
                'rnlink' => 'https://portal.ct.gov/DPH/Public-Health-Hearing-Office/Board-of-Examiners-for-Nursing/Board-of-Examiners-for-Nursing',
                'lpntemp' => '5 Days',
                'lpnperm' => '10 Days',
                'lpnfees' => '$150',
                'lpnnote' => 'null',
                'lpnlink' => 'https://portal.ct.gov/DPH/Public-Health-Hearing-Office/Board-of-Examiners-for-Nursing/Board-of-Examiners-for-Nursing',
                'cnatemp' => 'NA',
                'cnaperm' => '2 Weeks',
                'cnafees' => '$55',
                'cnanote' => 'Online Application',
                'cnalink' => 'https://portal.ct.gov/DPH/Practitioner-Licensing--Investigations/Nurseaide/Nurse-Aide-Registration',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'state' => 'Delaware',
                'rntemp' => '1 Week',
                'rnperm' => '4-7 Weeks',
                'rnfees' => '$132',
                'rnnote' => 'null',
                'rnlink' => 'https://dpr.delaware.gov/boards/nursing/',
                'lpntemp' => '1 Week',
                'lpnperm' => '2 Weeks',
                'lpnfees' => '$150',
                'lpnnote' => 'null',
                'lpnlink' => 'https://dpr.delaware.gov/boards/nursing/',
                'cnatemp' => 'NA',
                'cnaperm' => '2-3 Weeks',
                'cnafees' => '$30',
                'cnanote' => 'Mail in forms',
                'cnalink' => 'https://dhss.delaware.gov/dhcq/cnareg.html',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'state' => 'District Of Columbia',
                'rntemp' => '2-4 Weeks',
                'rnperm' => '2-6 Weeks',
                'rnfees' => '$230',
                'rnnote' => 'null',
                'rnlink' => 'https://dchealth.dc.gov/node/323012',
                'lpntemp' => 'NA',
                'lpnperm' => 'NA',
                'lpnfees' => '$230',
                'lpnnote' => 'Additional background check fee',
                'lpnlink' => 'https://dchealth.dc.gov/node/325772',
                'cnatemp' => 'NA',
                'cnaperm' => 'NA',
                'cnafees' => '$15',
                'cnanote' => 'null',
                'cnalink' => 'https://dchealth.dc.gov/node/149322',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'state' => 'Florida',
                'rntemp' => '4-6 Weeks',
                'rnperm' => '4-6 Weeks',
                'rnfees' => '$100',
                'rnnote' => 'Level 2 background fingerprints required to get license',
                'rnlink' => 'https://floridasnursing.gov/renewals/',
                'lpntemp' => 'NA',
                'lpnperm' => '30 Days',
                'lpnfees' => '$110',
                'lpnnote' => 'Other fees may apply',
                'lpnlink' => 'https://floridasnursing.gov/renewals/',
                'cnatemp' => 'Up to 3 Weeks',
                'cnaperm' => 'Up to 30 Days',
                'cnafees' => 'NA',
                'cnanote' => 'Fingerprint Fees Varies',
                'cnalink' => 'https://floridasnursing.gov/renewals/',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 =>
            array (
                'id' => 11,
                'state' => 'Georgia',
                'rntemp' => 'NA',
                'rnperm' => '4 Weeks',
                'rnfees' => '$90',
                'rnnote' => 'null',
                'rnlink' => 'https://sos.ga.gov/georgia-board-nursing',
                'lpntemp' => 'NA',
                'lpnperm' => '10-15 Days',
                'lpnfees' => '$75',
                'lpnnote' => 'null',
                'lpnlink' => 'https://sos.ga.gov/georgia-board-nursing',
                'cnatemp' => 'NA',
                'cnaperm' => '2 Weeks',
                'cnafees' => 'FREE',
                'cnanote' => 'null',
                'cnalink' => 'https://www.mmis.georgia.gov/portal/ResourceProxy.aspx?iCProxyTo=MS1OdXJzZUFpZGVTZWFyY2guYXNweA%3D%3D',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 =>
            array (
                'id' => 12,
                'state' => 'Hawaii',
                'rntemp' => '24 Hours',
                'rnperm' => '2 Weeks',
                'rnfees' => '$202 or $146',
                'rnnote' => 'Endorsement fee depends on even or odd year',
                'rnlink' => 'https://cca.hawaii.gov/pvl/boards/nursing/',
                'lpntemp' => '10-15 Days',
                'lpnperm' => '10-15 Days',
                'lpnfees' => '$146-$202',
                'lpnnote' => 'null',
                'lpnlink' => 'https://cca.hawaii.gov/pvl/boards/nursing/',
                'cnatemp' => 'NA',
                'cnaperm' => '2-3 Weeks',
                'cnafees' => '$25',
                'cnanote' => 'Mail in forms',
                'cnalink' => 'https://cca.hawaii.gov/pvl/programs/nurse/',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 =>
            array (
                'id' => 13,
                'state' => 'Idaho',
                'rntemp' => '24 Hours',
                'rnperm' => '2-4 Weeks',
                'rnfees' => '$152',
                'rnnote' => 'null',
                'rnlink' => 'https://dopl.idaho.gov/bon/bon-licensing/',
                'lpntemp' => 'NA',
                'lpnperm' => '6-8 Weeks',
                'lpnfees' => '$110',
                'lpnnote' => 'null',
                'lpnlink' => 'https://dopl.idaho.gov/bon/bon-licensing/',
                'cnatemp' => 'NA',
                'cnaperm' => '1 Month',
                'cnafees' => 'FREE',
                'cnanote' => 'null',
                'cnalink' => 'https://idahohealthcareinstitute.com/programs/cna/?gclid=CjwKCAiAjrarBhAWEiwA2qWdCNCChK_4EbhKlfzmYnQCDiXRVq_ejFM6T2u4egR8f6Kkp0w8l5vzYRoCAQsQAvD_BwE',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 =>
            array (
                'id' => 14,
                'state' => 'illinois',
                'rntemp' => '2-4 Weeks',
                'rnperm' => '4-6 Weeks',
                'rnfees' => '$50',
                'rnnote' => 'null',
                'rnlink' => 'https://www.idfpr.com/profs/Nursing.asp',
                'lpntemp' => '3-4 Weeks',
                'lpnperm' => '2-4 Weeks',
                'lpnfees' => '$75',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.idfpr.com/profs/Nursing.asp',
                'cnatemp' => 'NA',
                'cnaperm' => '1-3 Days',
                'cnafees' => '$25',
                'cnanote' => 'null',
                'cnalink' => 'https://hcwrpub.dph.illinois.gov/Search.aspx',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 =>
            array (
                'id' => 15,
                'state' => 'Indiana',
                'rntemp' => '1-2 Weeks',
                'rnperm' => '2-5 Weeks',
                'rnfees' => '$50',
                'rnnote' => 'null',
                'rnlink' => 'https://www.in.gov/pla/professions/indiana-state-board-of-nursing/',
                'lpntemp' => '10-14 Days',
                'lpnperm' => '4-5 Weeks',
                'lpnfees' => '$60',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.in.gov/pla/professions/indiana-state-board-of-nursing/',
                'cnatemp' => '2-6 Weeks',
                'cnaperm' => '4-12 Weeks',
                'cnafees' => '$65',
                'cnanote' => 'Mail in forms',
                'cnalink' => 'https://www.in.gov/health/ltc/aide-training-and-certification/cna/',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 =>
            array (
                'id' => 16,
                'state' => 'Iowa',
                'rntemp' => '1 Week',
                'rnperm' => '1-2 Weeks',
                'rnfees' => '$169',
                'rnnote' => 'null',
                'rnlink' => 'https://dial.iowa.gov/licenses/medical/nursing-professional-midwifery',
                'lpntemp' => '5-10 Days',
                'lpnperm' => '5-10 Days',
                'lpnfees' => '$169',
                'lpnnote' => 'null',
                'lpnlink' => 'https://dial.iowa.gov/licenses/medical/nursing-professional-midwifery',
                'cnatemp' => '3-5 Days',
                'cnaperm' => '1-2 Weeks',
                'cnafees' => 'FREE',
                'cnanote' => 'null',
                'cnalink' => 'https://dia-hfd.iowa.gov/',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 =>
            array (
                'id' => 17,
                'state' => 'Kansas',
                'rntemp' => '7-10 Days',
                'rnperm' => '30 Days',
                'rnfees' => '$125',
                'rnnote' => 'null',
                'rnlink' => 'https://ksbn.kansas.gov/renewal-application/',
                'lpntemp' => '1 Week',
                'lpnperm' => '4-6 Weeks',
                'lpnfees' => '$50',
                'lpnnote' => 'null',
                'lpnlink' => 'https://ksbn.kansas.gov/renewal-application/',
                'cnatemp' => 'NA',
                'cnaperm' => 'Exam / 3-4 Weeks after',
                'cnafees' => '$2-',
                'cnanote' => 'Must pass exam with 75%',
                'cnalink' => 'https://kdads.ks.gov/docs/librariesprovider17/survey-certification-and-credentialing-commission/health-occupations-credentialing/training-provider-information-resources-forms/nurse-aide/cna-instructor-manual.pdf?sfvrsn=dd9d07ee_2',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 =>
            array (
                'id' => 18,
                'state' => 'Kentucky',
                'rntemp' => 'NA',
                'rnperm' => '5-10 Weeks',
                'rnfees' => '$330',
                'rnnote' => 'null',
                'rnlink' => 'https://kybn.boardsofnursing.org/kybn',
                'lpntemp' => '10-14 Days',
                'lpnperm' => '4-6 Weeks',
                'lpnfees' => '$179.75',
                'lpnnote' => 'null',
                'lpnlink' => 'https://kybn.boardsofnursing.org/kybn',
                'cnatemp' => 'NA',
                'cnaperm' => '1-2 Weeks',
                'cnafees' => 'FREE',
                'cnanote' => 'null',
                'cnalink' => 'https://shorturl.at/fuBRW',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 =>
            array (
                'id' => 19,
                'state' => 'Louisiana',
                'rntemp' => '24 Hours',
                'rnperm' => '4-6 Weeks',
                'rnfees' => '$140',
                'rnnote' => 'Walkthrough with clean background. Temp cost and additional $100',
                'rnlink' => 'https://www.lsbn.state.la.us/applications/',
                'lpntemp' => 'Walkthrough',
                'lpnperm' => '12 Weeks',
                'lpnfees' => '$175.75',
                'lpnnote' => 'Temp last 12 weeks',
                'lpnlink' => 'https://www.lsbn.state.la.us/applications/',
                'cnatemp' => 'NA',
                'cnaperm' => 'NA',
                'cnafees' => '$35',
                'cnanote' => 'Mail in forms',
                'cnalink' => 'https://ldh.la.gov/page/nurse-aide-cna-training-and-certification',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 =>
            array (
                'id' => 20,
                'state' => 'Maine',
                'rntemp' => '7-10 Days',
                'rnperm' => '2-4 Weeks',
                'rnfees' => '$75',
                'rnnote' => 'null',
                'rnlink' => 'https://www.maine.gov/boardofnursing/',
                'lpntemp' => '7-14 Days',
                'lpnperm' => '1 Week',
                'lpnfees' => '$50',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.maine.gov/boardofnursing/',
                'cnatemp' => 'Can work 4 months not on registry 2 weeks',
                'cnaperm' => '4-6 Months',
                'cnafees' => '$20',
                'cnanote' => 'null',
                'cnalink' => 'https://www.maine.gov/dhhs/dlc/cna-registry',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 =>
            array (
                'id' => 21,
                'state' => 'Maryland',
                'rntemp' => '1-2 Weeks',
                'rnperm' => '3-4 Weeks',
                'rnfees' => '$100',
                'rnnote' => 'Can go inside state line to expedite fingerprints',
                'rnlink' => 'https://mbon.maryland.gov/Pages/default.aspx',
                'lpntemp' => 'Walkthrough',
                'lpnperm' => '4-6 Weeks',
                'lpnfees' => '$100',
                'lpnnote' => 'null',
                'lpnlink' => 'https://mbon.maryland.gov/Pages/default.aspx',
                'cnatemp' => 'NA',
                'cnaperm' => 'Up to 3 Months',
                'cnafees' => '$20',
                'cnanote' => 'Additional fingerprint fees',
                'cnalink' => 'https://mbon.maryland.gov/Pages/default.aspx',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 =>
            array (
                'id' => 22,
                'state' => 'Massachusetts',
                'rntemp' => 'NA',
                'rnperm' => '2-4 Weeks',
                'rnfees' => '$275',
                'rnnote' => 'null',
                'rnlink' => 'https://www.mass.gov/how-to/renew-your-nursing-license',
                'lpntemp' => 'NA',
                'lpnperm' => '4 Weeks',
                'lpnfees' => '$275',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.mass.gov/how-to/renew-your-nursing-license',
                'cnatemp' => 'NA',
                'cnaperm' => '3 Weeks',
                'cnafees' => 'FREE',
                'cnanote' => 'null',
                'cnalink' => 'https://nursinglicensemap.com/nursing-specialties/certified-nursing-assistant/',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 =>
            array (
                'id' => 23,
                'state' => 'Michigan',
                'rntemp' => '4 Weeks',
                'rnperm' => '4 Weeks',
                'rnfees' => '$64',
                'rnnote' => 'null',
                'rnlink' => 'https://www.michigan.gov/lara/bureau-list/bpl/miplus-assistant',
                'lpntemp' => 'NA',
                'lpnperm' => '6-8 Weeks',
                'lpnfees' => '$54',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.michigan.gov/lara/bureau-list/bpl/miplus-assistant',
                'cnatemp' => 'NA',
                'cnaperm' => 'Exam / 2 Weeks after',
                'cnafees' => 'Fees Vary',
                'cnanote' => 'Certain states require training program',
                'cnalink' => 'https://www.midmich.edu/academics/programs-of-study/health-sciences/cna?utm_campaign=Certified+Nursing+Aide+Program&utm_source=google&utm_medium=ppc&utm_term=certified%20nursing%20assistant&utm_content=1942502-e1-ng-mp-c898482186-g48602246121-a304985415733-uCjwKCAiAjrarBhAWEiwA2qWdCLE1avmUoNds-6Nq5jXCQXRWT-XRHf1yiDRfLcYX_qoJ7PTI53LKARoCt6wQAvD_BwE-cat5499170-kcertified%20nursing%20assistant-mod&gad_source=1',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 =>
            array (
                'id' => 24,
                'state' => 'Minnesota',
                'rntemp' => '2-3 Weeks',
                'rnperm' => '4-6 Weeks',
                'rnfees' => '$105',
                'rnnote' => 'null',
                'rnlink' => 'https://mn.gov/boards/nursing/licensure/license-renewal/',
                'lpntemp' => '1-5 Days',
                'lpnperm' => 'Varies',
                'lpnfees' => '$115',
                'lpnnote' => 'Temp lasts 60 days',
                'lpnlink' => 'https://mn.gov/boards/nursing/licensure/license-renewal/',
                'cnatemp' => 'NA',
                'cnaperm' => '2-4 Weeks',
                'cnafees' => 'FREE',
                'cnanote' => 'Must mail in',
                'cnalink' => 'https://www.ohe.state.mn.us/dPg.cfm?pageID=2481',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 =>
            array (
                'id' => 25,
                'state' => 'Mississippi',
                'rntemp' => '5 Days',
                'rnperm' => '7-10 Days',
                'rnfees' => '$100',
                'rnnote' => 'null',
                'rnlink' => 'https://www.msbn.ms.gov/licensure/applications-and-forms',
                'lpntemp' => '5 Days',
                'lpnperm' => '2-3 Weeks',
                'lpnfees' => 'NA',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.msbn.ms.gov/home/lpn-education',
                'cnatemp' => 'NA',
                'cnaperm' => '2-4 Weeks',
                'cnafees' => '$26',
            'cnanote' => 'Must have verification of paid employment within last 24 months (ex: pay stub, w2, etc)',
                'cnalink' => 'https://shorturl.at/aeAMZ',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 =>
            array (
                'id' => 26,
                'state' => 'Missouri',
                'rntemp' => '24 Hours',
                'rnperm' => '3-4 Weeks',
                'rnfees' => '$55',
                'rnnote' => 'null',
                'rnlink' => 'https://pr.mo.gov/nursing-licensure-rn.asp',
                'lpntemp' => 'Walkthrough',
                'lpnperm' => '2-3 Weeks',
                'lpnfees' => '$95.80',
                'lpnnote' => 'null',
                'lpnlink' => 'https://pr.mo.gov/nursing-licensure-lpn.asp',
                'cnatemp' => '2-3 Weeks',
                'cnaperm' => 'Exam / 2-3 Weeks after',
                'cnafees' => 'Fees Vary',
                'cnanote' => 'null',
                'cnalink' => 'https://health.mo.gov/safety/cnaregistry/cna.php',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 =>
            array (
                'id' => 27,
                'state' => 'Montana',
                'rntemp' => '2-3 Weeks',
                'rnperm' => '3-6 Weeks',
                'rnfees' => '$200',
                'rnnote' => 'Must verify all licenses held temp or expired',
                'rnlink' => 'https://boards.bsd.dli.mt.gov/nursing/',
                'lpntemp' => '4-6 Weeks',
                'lpnperm' => '10 Days',
                'lpnfees' => '$227.25',
                'lpnnote' => 'Fingerprint and Background Fees',
                'lpnlink' => 'https://boards.bsd.dli.mt.gov/nursing/',
                'cnatemp' => 'NA',
                'cnaperm' => '1-2 Weeks',
                'cnafees' => 'FREE',
                'cnanote' => 'null',
                'cnalink' => 'https://dphhs.mt.gov/qad/certification/can',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 =>
            array (
                'id' => 28,
                'state' => 'Nebraska',
                'rntemp' => '3 Weeks',
                'rnperm' => '8 Weeks',
                'rnfees' => '$125',
                'rnnote' => 'null',
                'rnlink' => 'http://dhhs.ne.gov/licensure/Pages/Nurse-Licensing.aspx',
                'lpntemp' => '3-6 Weeks',
                'lpnperm' => '2-8 Weeks',
                'lpnfees' => '$59.50 - $151.75',
                'lpnnote' => 'null',
                'lpnlink' => 'http://dhhs.ne.gov/licensure/Pages/Nurse-Licensing.aspx',
                'cnatemp' => 'NA',
                'cnaperm' => '2-4 Weeks',
                'cnafees' => '$20 course',
                'cnanote' => 'null',
                'cnalink' => 'https://dhhs.ne.gov/licensure/Pages/Nurse-Aide-Requirements.aspx',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 =>
            array (
                'id' => 29,
                'state' => 'Nevada',
                'rntemp' => '1-5 Days',
                'rnperm' => '4-5 Weeks',
                'rnfees' => '$105',
                'rnnote' => 'null',
                'rnlink' => 'https://nevadanursingboard.org/wp-content/uploads/2023/11/RNLPN-Exam-Instructions.pdf',
                'lpntemp' => '1 Week',
                'lpnperm' => 'NA',
                'lpnfees' => '$145',
                'lpnnote' => 'null',
                'lpnlink' => 'https://nevadanursingboard.org/wp-content/uploads/2023/11/RNLPN-Exam-Instructions.pdf',
                'cnatemp' => '1 Week',
                'cnaperm' => '2-4 Months',
                'cnafees' => '$101',
                'cnanote' => 'Fingerprinting Fee',
                'cnalink' => 'https://nevadanursingboard.org/wp-content/uploads/2023/11/CNA-Exam-Instructions.pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 =>
            array (
                'id' => 30,
                'state' => 'New Hampshire',
                'rntemp' => '6-9 Weeks',
                'rnperm' => '6-9 Weeks',
                'rnfees' => '$120',
                'rnnote' => 'null',
                'rnlink' => 'https://www.oplc.nh.gov/applications-rn',
                'lpntemp' => '8 Weeks',
                'lpnperm' => '8 Weeks',
                'lpnfees' => '$167',
                'lpnnote' => 'Temp valid for 120 days',
                'lpnlink' => 'https://www.oplc.nh.gov/applications-lpn',
                'cnatemp' => 'NA',
                'cnaperm' => '4-6 Weeks',
                'cnafees' => '$82',
                'cnanote' => 'Fingerprinting Fee',
                'cnalink' => 'https://www.oplc.nh.gov/applications-lna',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 =>
            array (
                'id' => 31,
                'state' => 'New Jersey',
                'rntemp' => 'NA',
                'rnperm' => '2-4 Months',
                'rnfees' => '$200',
                'rnnote' => 'null',
                'rnlink' => 'https://www.njconsumeraffairs.gov/nur/Pages/applications.aspx',
                'lpntemp' => 'NA',
                'lpnperm' => '4-6 Weeks',
                'lpnfees' => '$261.44',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.njconsumeraffairs.gov/nur/Pages/applications.aspx',
                'cnatemp' => '120 Days',
                'cnaperm' => '4-6  Weeks',
                'cnafees' => '$30',
                'cnanote' => 'Some states do not transfer, Call 1-877-774-4243',
                'cnalink' => 'https://www.nj.gov/health/healthfacilities/certification-licensing/nurse-aide-pc-assistant/apply/index.shtml',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 =>
            array (
                'id' => 32,
                'state' => 'New Mexico',
                'rntemp' => 'NA',
                'rnperm' => '4-6 Weeks',
                'rnfees' => '$110',
                'rnnote' => 'null',
                'rnlink' => 'https://www.bon.nm.gov/',
                'lpntemp' => '2 Weeks',
                'lpnperm' => '2 Weeks',
                'lpnfees' => '$115',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.bon.nm.gov/',
                'cnatemp' => 'NA',
                'cnaperm' => '3-4 Weeks',
                'cnafees' => 'FREE',
                'cnanote' => 'Current CNA certification, Social Security Card, Driver License and Mailing Address to ATTN Nurse Aide Registry PO Box 26110 Santa',
                'cnalink' => 'https://www.nursinglicensure.org/cna/new-mexico-nursing-assistant/',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            32 =>
            array (
                'id' => 33,
                'state' => 'New York',
                'rntemp' => 'NA',
                'rnperm' => '6-8 Weeks',
                'rnfees' => '$143',
                'rnnote' => 'null',
                'rnlink' => 'https://www.op.nysed.gov/registered-professional-nursing',
                'lpntemp' => 'NA',
                'lpnperm' => '6-8 Weeks',
                'lpnfees' => '$178',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.op.nysed.gov/licensed-practical-nurses',
                'cnatemp' => 'NA',
                'cnaperm' => '1-2 Weeks',
                'cnafees' => '$50',
                'cnanote' => 'null',
                'cnalink' => 'https://www.nysed.gov/career-technical-education/nurse-assisting-nurse-aide',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 =>
            array (
                'id' => 34,
                'state' => 'North Carolina',
                'rntemp' => '8 Days',
                'rnperm' => '6 Weeks',
                'rnfees' => '$150',
                'rnnote' => 'The Board processes licenses on Tuesday and Wednesday. If they submit on one of these days, they will receive license by Saturday-if they have a clean background',
                'rnlink' => 'https://www.ncbon.com/licensure-listing-apply-renewal-reinstatement-rn-lpn',
                'lpntemp' => '2-3 Days',
                'lpnperm' => '6-8 Weeks',
                'lpnfees' => '$150',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.ncbon.com/licensure-listing-apply-renewal-reinstatement-rn-lpn',
                'cnatemp' => '4-6 Weeks',
                'cnaperm' => 'Exam / 4-6 Weeks After',
                'cnafees' => '$101',
                'cnanote' => 'No reciprocity/endorsement or transfer from other states. Must pass exam',
                'cnalink' => 'https://ncnar.ncdhhs.gov/ncna.html',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            34 =>
            array (
                'id' => 35,
                'state' => 'North Dakota',
                'rntemp' => '3 Days',
                'rnperm' => '3 Days',
                'rnfees' => '$160',
                'rnnote' => 'null',
                'rnlink' => 'https://www.ndbon.org/NurseLicensure/InitialEndorse/index.asp',
                'lpntemp' => '1 Week',
                'lpnperm' => '2 Weeks',
                'lpnfees' => '$160',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.ndbon.org/NurseLicensure/InitialEndorse/index.asp',
                'cnatemp' => '10 Days',
                'cnaperm' => '2-4 Weeks',
                'cnafees' => 'FREE',
                'cnanote' => 'null',
                'cnalink' => 'https://www.hhs.nd.gov/certified-nurse-aid-information',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 =>
            array (
                'id' => 36,
                'state' => 'Ohio',
                'rntemp' => 'NA',
                'rnperm' => '4-6 Weeks',
                'rnfees' => '$75',
                'rnnote' => 'null',
                'rnlink' => 'http://www.nursing.ohio.gov/',
                'lpntemp' => 'NA',
                'lpnperm' => 'NA',
                'lpnfees' => '$75',
                'lpnnote' => 'Must complete 2 hours of continuing education',
                'lpnlink' => 'http://www.nursing.ohio.gov/PDFS/Education/Category_A_Law_Rules.pdf, http://www.nursing.ohio.gov/forms.htm#ExamEndorseForms',
                'cnatemp' => 'NA',
                'cnaperm' => '1-2 Weeks',
                'cnafees' => 'FREE',
                'cnanote' => 'Contact the OH Department of Health. Contact Number: 800-582-5908 or 614-752-9500',
                'cnalink' => 'http://www.nursing.ohio.gov/forms.htm#ExamEndorseForms',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 =>
            array (
                'id' => 37,
                'state' => 'Oklahoma',
                'rntemp' => '3-4 Weeks',
                'rnperm' => '4-6 Weeks',
                'rnfees' => '$85',
                'rnnote' => 'Timeframe is with a CLEAN background',
                'rnlink' => 'https://oklahoma.gov/nursing.html',
                'lpntemp' => '2 Weeks',
                'lpnperm' => '2 Weeks',
                'lpnfees' => '$95',
                'lpnnote' => 'null',
                'lpnlink' => 'https://oklahoma.gov/nursing.html',
                'cnatemp' => 'NA',
                'cnaperm' => '1-2 Weeks',
                'cnafees' => 'FREE',
                'cnanote' => 'Main in forms',
                'cnalink' => 'https://oklahoma.gov/careertech/testing-center/health-professional-certifications/nurse-aide.html',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            37 =>
            array (
                'id' => 38,
                'state' => 'Oregon',
                'rntemp' => 'NA',
                'rnperm' => '3-4 Weeks',
                'rnfees' => '$245',
                'rnnote' => 'null',
                'rnlink' => 'https://www.oregon.gov/OSBN/Pages/index.aspx',
                'lpntemp' => 'NA',
                'lpnperm' => '3-4 Weeks',
                'lpnfees' => '$268.50',
                'lpnnote' => 'Home states verification fee',
                'lpnlink' => 'https://www.oregon.gov/OSBN/Pages/index.aspx',
                'cnatemp' => 'NA',
                'cnaperm' => '4-6 Weeks',
                'cnafees' => '$60',
                'cnanote' => 'Fingerprinting Fee $52',
                'cnalink' => 'https://osbn.oregon.gov/OBNPortal/DesktopDefault.aspx?tabindex=0&tabid=5&utyp=4',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            38 =>
            array (
                'id' => 39,
                'state' => 'Pennsylvania',
                'rntemp' => '3-6 Weeks',
                'rnperm' => '6 Weeks',
                'rnfees' => '$100',
                'rnnote' => 'null',
                'rnlink' => 'https://www.dos.pa.gov/ProfessionalLicensing/BoardsCommissions/Nursing/Pages/General-Information.aspx',
                'lpntemp' => '7-10 Days',
                'lpnperm' => '6-8 Weeks',
                'lpnfees' => '$155',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.dos.pa.gov/ProfessionalLicensing/BoardsCommissions/Nursing/Pages/General-Information.aspx',
                'cnatemp' => 'Work up to 120 days',
                'cnaperm' => '2-4 Weeks',
                'cnafees' => 'FREE',
                'cnanote' => 'Online Application',
                'cnalink' => 'https://www.education.pa.gov/K-12/Career%20and%20Technical%20Education/Nurse%20Aide%20Training%20Program/Pages/default.aspx',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 =>
            array (
                'id' => 40,
                'state' => 'Rhode Island',
                'rntemp' => '6-8 Weeks',
                'rnperm' => '8-10 Weeks',
                'rnfees' => '$135',
                'rnnote' => 'null',
                'rnlink' => 'https://health.ri.gov/licenses/detail.php?id=231',
                'lpntemp' => 'NA',
                'lpnperm' => '8 Weels',
                'lpnfees' => 'NA',
                'lpnnote' => 'null',
                'lpnlink' => 'https://health.ri.gov/licenses/detail.php?id=231',
                'cnatemp' => 'NA',
                'cnaperm' => '8 Weeks',
                'cnafees' => '$35',
                'cnanote' => 'Mail in only',
                'cnalink' => 'https://health.ri.gov/licenses/detail.php?id=232',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            40 =>
            array (
                'id' => 41,
                'state' => 'South Carolina',
                'rntemp' => '24 Hours',
                'rnperm' => '2 Weeks',
                'rnfees' => '$100',
                'rnnote' => 'null',
                'rnlink' => 'https://eservice.llr.sc.gov/SSO/Login/LoginPage?ReturnUrl=%2fOnlineRenewals%2f',
                'lpntemp' => 'NA',
                'lpnperm' => '6-8 Weeks',
                'lpnfees' => '$110',
                'lpnnote' => 'null',
                'lpnlink' => 'https://eservice.llr.sc.gov/SSO/Login/LoginPage?ReturnUrl=%2fOnlineRenewals%2f',
                'cnatemp' => 'NA',
                'cnaperm' => 'Exam / 7-10 Days',
                'cnafees' => 'FREE',
                'cnanote' => 'Online Application',
                'cnalink' => 'https://www.scdhhs.gov/sites/default/files/SC%20Nurse%20Aide%20Training%20Program%20Policies%20copy.pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 =>
            array (
                'id' => 42,
                'state' => 'South Dakota',
                'rntemp' => '24 Hours',
                'rnperm' => '3-6 Weeks',
                'rnfees' => '$100',
                'rnnote' => 'null',
                'rnlink' => 'https://doh.sd.gov/licensing-and-records/boards/nursing/nursing-licensure-registration-and-renewal-requirements/rn-lpn-licensure-procedures/',
                'lpntemp' => '3-6 Weeks',
                'lpnperm' => 'null',
                'lpnfees' => '$100',
                'lpnnote' => 'Temp is good for 90 days',
                'lpnlink' => 'https://doh.sd.gov/licensing-and-records/boards/nursing/nursing-licensure-registration-and-renewal-requirements/rn-lpn-licensure-procedures/',
                'cnatemp' => 'Work up to 120 days',
                'cnaperm' => '1-2 Weeks',
                'cnafees' => 'FREE',
                'cnanote' => 'null',
                'cnalink' => 'https://doh.sd.gov/licensing-and-records/boards/nursing/nursing-licensure-registration-and-renewal-requirements/cna-registration-procedures/',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 =>
            array (
                'id' => 43,
                'state' => 'Tennessee',
                'rntemp' => 'NA',
                'rnperm' => '4-6 Weeks',
                'rnfees' => '$115',
                'rnnote' => 'null',
                'rnlink' => 'https://www.tn.gov/content/dam/tn/health/healthprofboards/nursing/applications/RN-LPN%20Instructions%20for%20Endorsement.pdf',
                'lpntemp' => '4-6 Weeks',
                'lpnperm' => '6-8 Weeks',
                'lpnfees' => '$115',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.tn.gov/content/dam/tn/health/healthprofboards/nursing/applications/RN-LPN%20Instructions%20for%20Endorsement.pdf',
                'cnatemp' => 'NA',
                'cnaperm' => '5-7 Days',
                'cnafees' => '$20',
                'cnanote' => 'Mail in only',
                'cnalink' => 'https://www.tn.gov/health/health-professionals/hcf-main/nai.html',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 =>
            array (
                'id' => 44,
                'state' => 'Texas',
                'rntemp' => '15 Days',
                'rnperm' => '15 Days',
                'rnfees' => '$150 for Endorsement, $75 for Exams',
                'rnnote' => 'null',
                'rnlink' => 'https://www.bon.texas.gov/texasnurseportal/index.html',
                'lpntemp' => '10 Days',
                'lpnperm' => '10 Days',
                'lpnfees' => '$111',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.bon.texas.gov/texasnurseportal/index.html',
                'cnatemp' => '6-8 Weeks',
                'cnaperm' => '10 Days',
                'cnafees' => 'FREE',
                'cnanote' => 'Fingerprinting Fee',
                'cnalink' => 'https://txhhs.my.site.com/TULIP/s/login/',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 =>
            array (
                'id' => 45,
                'state' => 'Utah',
                'rntemp' => 'NA',
                'rnperm' => '10-15 Days',
                'rnfees' => '$100',
                'rnnote' => 'null',
                'rnlink' => 'https://dopl.utah.gov/nursing/renew-a-license/registered-nurse-or-licensed-practice-nurse/',
                'lpntemp' => 'NA',
                'lpnperm' => '2-3 Weeks',
                'lpnfees' => '$100',
                'lpnnote' => 'null',
                'lpnlink' => 'https://dopl.utah.gov/nursing/renew-a-license/registered-nurse-or-licensed-practice-nurse/',
                'cnatemp' => 'NA',
                'cnaperm' => '1-2 Weeks',
                'cnafees' => '$40',
                'cnanote' => 'null',
                'cnalink' => 'http://www.utahcna.com/docs/Reciprocity%20Application.pdf',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 =>
            array (
                'id' => 46,
                'state' => 'Vermont',
                'rntemp' => 'NA',
                'rnperm' => '3-5 Days',
                'rnfees' => '$150',
                'rnnote' => 'null',
                'rnlink' => 'https://sos.vermont.gov/nursing/apply-renew/',
                'lpntemp' => 'Walkthrough',
                'lpnperm' => '3-6 Days',
                'lpnfees' => '$150',
                'lpnnote' => 'null',
                'lpnlink' => 'https://sos.vermont.gov/nursing/apply-renew/',
                'cnatemp' => '2-5 Days',
                'cnaperm' => '1-3 Weeks',
                'cnafees' => '$20',
                'cnanote' => 'null',
                'cnalink' => 'https://dlp.vermont.gov/survey-cert/natcep-forms',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 =>
            array (
                'id' => 47,
                'state' => 'Virginia',
                'rntemp' => 'NA',
                'rnperm' => '45 Days',
                'rnfees' => '$190',
                'rnnote' => 'null',
                'rnlink' => 'https://www.dhp.virginia.gov/Boards/Nursing/ApplicantResources/ApplyforLicense/',
                'lpntemp' => '3-5 Days',
                'lpnperm' => '2-6 Weeks',
                'lpnfees' => '$170',
                'lpnnote' => 'null',
                'lpnlink' => 'https://www.dhp.virginia.gov/Boards/Nursing/ApplicantResources/ApplyforLicense/',
                'cnatemp' => '1-3 Months',
                'cnaperm' => '1-3 Months',
                'cnafees' => 'FREE',
                'cnanote' => 'Apps must be sent to the board',
                'cnalink' => 'https://www.dhp.virginia.gov/Boards/Nursing/ApplicantResources/ApplyforLicense/NurseAide/',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 =>
            array (
                'id' => 48,
                'state' => 'Washington',
                'rntemp' => '3-4 Weeks',
                'rnperm' => '4-6 Weeks',
                'rnfees' => '$120',
                'rnnote' => 'null',
                'rnlink' => 'https://nursing.wa.gov/licensing/apply-license/rn-or-lpn-license',
                'lpntemp' => 'NA',
                'lpnperm' => '4-6 Weeks',
                'lpnfees' => '$88',
                'lpnnote' => 'null',
                'lpnlink' => 'https://nursing.wa.gov/licensing/apply-license/rn-or-lpn-license',
                'cnatemp' => 'NA',
                'cnaperm' => 'Up to 3 Weeks',
                'cnafees' => '$97',
                'cnanote' => 'Fingerprinting Fee',
                'cnalink' => 'https://doh.wa.gov/licenses-permits-and-certificates/professions-new-renew-or-update/nursing-assistant/licensing-information',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 =>
            array (
                'id' => 49,
                'state' => 'West Virginia',
                'rntemp' => '5-7 Days',
                'rnperm' => '3-4 Weeks',
                'rnfees' => '$100',
                'rnnote' => '5-7 days for temp if SPOTLESS background. Must apply for Temp and Perm at the same time for $125',
                'rnlink' => 'https://wvrnboard.wv.gov/Pages/Resources.aspx',
                'lpntemp' => '5-7 Days',
                'lpnperm' => '7-10 Days',
                'lpnfees' => '$51-$81',
                'lpnnote' => 'Renew every Oct 31',
                'lpnlink' => 'http://www.lpnboard.state.wv.us/',
                'cnatemp' => 'NA',
                'cnaperm' => '1-2 Weeks',
                'cnafees' => 'FREE',
                'cnanote' => 'Mail in only',
                'cnalink' => 'https://ohflac.wvdhhr.org/Programs/NA.html',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 =>
            array (
                'id' => 50,
                'state' => 'Wisconsin',
                'rntemp' => 'NA',
                'rnperm' => '3-6 Weeks',
                'rnfees' => '$82',
                'rnnote' => 'null',
                'rnlink' => 'https://dsps.wi.gov/pages/BoardsCouncils/Nursing/Default.aspx',
                'lpntemp' => '5-6 Weeks',
                'lpnperm' => '5-6 Weeks',
                'lpnfees' => '$92',
                'lpnnote' => 'null',
                'lpnlink' => 'https://dsps.wi.gov/pages/BoardsCouncils/Nursing/Default.aspx',
                'cnatemp' => '2-3 Weeks',
                'cnaperm' => '2-3 Weeks',
                'cnafees' => 'FREE',
                'cnanote' => 'Mail in only',
                'cnalink' => 'https://www.dhs.wisconsin.gov/caregiver/nurse-aide/nurse-aide.htm',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            50 =>
            array (
                'id' => 51,
                'state' => 'Wyoming',
                'rntemp' => '2-5 Days',
                'rnperm' => '4-8 Weeks',
                'rnfees' => '$135',
                'rnnote' => 'null',
                'rnlink' => 'http://nursing.state.wy.us/',
                'lpntemp' => '7-10 Days',
                'lpnperm' => '2 Weeks',
                'lpnfees' => '$185',
                'lpnnote' => 'null',
                'lpnlink' => 'http://nursing.state.wy.us/',
                'cnatemp' => 'Up to 3 Weeks',
                'cnaperm' => '2-4 Months',
                'cnafees' => '$150',
                'cnanote' => 'Fingerprinting Fee, Online Application',
                'cnalink' => 'http://nursing.state.wy.us/',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));


    }
}
