<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StatenursingTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('statenursing')->delete();
        
        \DB::table('statenursing')->insert(array (
            0 => 
            array (
                'cnafees' => 'NA',
            'cnalink' => 'https://dph1.adph.state.al.us/NurseAideRegistry/(S(v343yoifoejr2lrydzh2cw32))/FAQ.aspx#anchor17',
                'cnanote' => 'No endorsement/reciprocity. Employer must get you on the registry.',
                'cnaperm' => 'NA',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 1,
                'lpnfees' => '$138.50',
                'lpnlink' => 'https://abn.alabama.gov/abnonline/ABNOnline_Endorsement.aspx',
                'lpnnote' => 'Temp lasts 90 days',
                'lpnperm' => '4-6 Weeks',
                'lpntemp' => '14 Days',
                'rnfees' => '$85',
                'rnlink' => 'https://www.abn.alabama.gov/',
                'rnnote' => 'null',
                'rnperm' => '1 Month',
                'rntemp' => '3-5 Days',
                'state' => 'Alabama',
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'cnafees' => '$260-$330',
                'cnalink' => 'https://www.commerce.alaska.gov/web/portals/5/pub/nua4070.pdf',
                'cnanote' => 'Can work 120 without cert., but must have application in process',
                'cnaperm' => 'null',
                'cnatemp' => 'Can work 4 months not on registry 2 weeks',
                'created_at' => NULL,
                'id' => 2,
                'lpnfees' => '$375',
                'lpnlink' => 'https://www.commerce.alaska.gov/web/portals/5/pub/nur4014.pdf',
                'lpnnote' => 'Temp valid for 6 months',
                'lpnperm' => '6-8 Weeks',
                'lpntemp' => '10 Days',
                'rnfees' => '$375',
                'rnlink' => 'https://www.commerce.alaska.gov/web/portals/5/pub/nur4016.pdf',
                'rnnote' => 'null',
                'rnperm' => '4-6 Weeks',
                'rntemp' => '3-4 Weeks',
                'state' => 'Alaska',
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'cnafees' => '$50',
                'cnalink' => 'https://azbn.boardsofnursing.org/azbn',
                'cnanote' => 'Online Application',
                'cnaperm' => '4-6 Months',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 3,
                'lpnfees' => '$50',
                'lpnlink' => 'https://www.azbn.gov/licensure-certification/application-instructions/rn-lpn-endorsement',
                'lpnnote' => 'null',
                'lpnperm' => '2-3 Months',
                'lpntemp' => '48+ hour walkthrough',
                'rnfees' => '$150',
                'rnlink' => 'http://www.azbn.gov/',
                'rnnote' => '2 days if contract in hand',
                'rnperm' => '4-8 Weeks',
                'rntemp' => '2-4 Weeks',
                'state' => 'Arizona',
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://view.officeapps.live.com/op/view.aspx?src=http%3A%2F%2Fhumanservices.arkansas.gov%2Fimages%2Fuploads%2Fdms%2Fdms_798.docx',
                'cnanote' => 'null',
                'cnaperm' => '2 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 4,
                'lpnfees' => '$125',
                'lpnlink' => 'https://www.arsbn.org/endorsement',
                'lpnnote' => 'Temp lasts 6 months',
                'lpnperm' => '10 Weeks',
                'lpntemp' => '3-4 Days',
                'rnfees' => '$100',
                'rnlink' => 'null',
                'rnnote' => 'null',
                'rnperm' => '1 AWeek',
                'rntemp' => '1 Week',
                'state' => 'Arkansas',
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'cnafees' => 'NA',
                'cnalink' => 'https://www.cdph.ca.gov/CDPH%20Document%20Library/ControlledForms/cdph283b.pdf',
                'cnanote' => 'Fingerprint fee - must be done in CA',
                'cnaperm' => 'Varies',
                'cnatemp' => '4-8 Weeks',
                'created_at' => NULL,
                'id' => 5,
                'lpnfees' => '$200',
                'lpnlink' => 'http://www.bvnpt.ca.gov/applicants/application_for_vocational_nurse_licensure_by_endorsement.shtml',
                'lpnnote' => 'null',
                'lpnperm' => '6 Months',
                'lpntemp' => '6-10 Weeks',
                'rnfees' => '$400-$450',
                'rnlink' => 'https://www.rn.ca.gov/',
                'rnnote' => 'null',
                'rnperm' => '3-6 Months',
                'rntemp' => '3-4 Months',
                'state' => 'California',
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'cnafees' => '$10',
                'cnalink' => 'https://apps.colorado.gov/dora/licensing/Default.aspx',
                'cnanote' => 'Online Application',
                'cnaperm' => '3-4 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 6,
                'lpnfees' => '$43',
                'lpnlink' => 'https://www.colorado.gov/pacific/dora/Nursing_LPN_Applications_Docs',
                'lpnnote' => 'null',
                'lpnperm' => '3-4 Weeks',
                'lpntemp' => '1-2 Weeks',
                'rnfees' => '$127',
                'rnlink' => '',
                'rnnote' => 'Receive Temp and Perm atthe same time',
                'rnperm' => '3-5 Weeks',
                'rntemp' => '3-5 Weeks',
                'state' => 'Colorado',
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'cnafees' => '$55',
                'cnalink' => 'https://oap.prometric.com/CandidateWeb/Login/Login.aspx?ReturnUrl=%2fCandidateWeb%2fforms%2fCTNURS%2fConnecticutNurseAideRegistryApplication.aspx',
                'cnanote' => 'Online Application',
                'cnaperm' => '2 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 7,
                'lpnfees' => '$150',
                'lpnlink' => 'https://www.arsbn.org/endorsement',
                'lpnnote' => 'null',
                'lpnperm' => '10 Days',
                'lpntemp' => '5 Days',
                'rnfees' => '$180',
                'rnlink' => 'null',
            'rnnote' => '3-5 days for temporary (good for 120 days), signed agreement with NURSYS',
                'rnperm' => '7-10 Days',
                'rntemp' => '3-5 Days',
                'state' => 'Connecticut',
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'cnafees' => '$30',
                'cnalink' => 'https://www.prometric.com/en-us/clients/nurseaide/documents/delaware/ReciprocityApplication.pdf',
                'cnanote' => 'Mail in forms',
                'cnaperm' => '2-3 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 8,
                'lpnfees' => '$150',
                'lpnlink' => 'https://dpr.delaware.gov/boards/nursing/forms/',
                'lpnnote' => 'null',
                'lpnperm' => '2 Weeks',
                'lpntemp' => '1 Week',
                'rnfees' => '$132',
                'rnlink' => 'https://dpr.delaware.gov/boards/nursing/forms/',
                'rnnote' => 'null',
                'rnperm' => '4-7 Weeks',
                'rntemp' => '1 Week',
                'state' => 'Delaware',
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'cnafees' => '$15',
                'cnalink' => 'https://doh.dc.gov/sites/default/files/dc/sites/doh/publication/attachments/Nursing_Application_for_Nurse_Aide_Certification_by_Endorsement_-_PDF_Version.pdf',
                'cnanote' => 'null',
                'cnaperm' => 'NA',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 9,
                'lpnfees' => '$230',
                'lpnlink' => 'https://doh.dc.gov/sites/default/files/dc/sites/doh/publication/attachments/16%20RN-LPN%20Endorsement%20Application.pdf',
                'lpnnote' => 'Additional background check fee',
                'lpnperm' => 'NA',
                'lpntemp' => 'NA',
                'rnfees' => '$230',
                'rnlink' => 'https://dchealth.dc.gov/',
                'rnnote' => 'null',
                'rnperm' => '2-6 Weeks',
                'rntemp' => '2-4 Weeks',
                'state' => 'District Of Columbia',
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'cnafees' => 'NA',
                'cnalink' => 'https://floridasnursing.gov/applications/cna-reciprocity-app.pdf',
                'cnanote' => 'Fingerprint Fees Varies',
                'cnaperm' => 'Up to 30 Days',
                'cnatemp' => 'Up to 3 Weeks',
                'created_at' => NULL,
                'id' => 10,
                'lpnfees' => '$110',
                'lpnlink' => 'https://floridasnursing.gov/licensing/licensed-practical-nurse-registered-nurse-by-endorsement/',
                'lpnnote' => 'Other fees may apply',
                'lpnperm' => '30 Days',
                'lpntemp' => 'NA',
                'rnfees' => '$100',
                'rnlink' => 'http://www.floridahealth.gov/licensing-and-regulation/index.html',
                'rnnote' => 'Level 2 background fingerprints required to get license',
                'rnperm' => '4-6 Weeks',
                'rntemp' => '4-6 Weeks',
                'state' => 'Florida',
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://www.mmis.georgia.gov/portal/ResourceProxy.aspx?iCProxyTo=MS1BdHRhY2htZW50cy9Gb3Jtcy9SZWNpcHJvY2l0eSUyMEZvcm0ucGRm',
                'cnanote' => 'null',
                'cnaperm' => '2 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 11,
                'lpnfees' => '$75',
                'lpnlink' => 'http://sos.ga.gov/acrobat/PLB/13%20LPN%20Endorsement%20Application.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '10-15 Days',
                'lpntemp' => 'NA',
                'rnfees' => '$90',
                'rnlink' => 'http://sos.ga.gov/index.php/licensing/plb/45',
                'rnnote' => 'null',
                'rnperm' => '4 Weeks',
                'rntemp' => 'NA',
                'state' => 'Georgia',
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'cnafees' => '$25',
                'cnalink' => 'https://www.prometric.com/en-us/clients/nurseaide/documents/hawaii/HI_CNA_APP.pdf',
                'cnanote' => 'Mail in forms',
                'cnaperm' => '2-3 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 12,
                'lpnfees' => '$146-$202',
                'lpnlink' => 'http://cca.hawaii.gov/pvl/boards/nursing/application_publications/',
                'lpnnote' => 'null',
                'lpnperm' => '10-15 Days',
                'lpntemp' => '10-15 Days',
                'rnfees' => '$202 or $146',
                'rnlink' => 'http://cca.hawaii.gov/pvl/boards/nursing/application_publications/',
                'rnnote' => 'Endorsement fee depends on even or odd year',
                'rnperm' => '2 Weeks',
                'rntemp' => '24 Hours',
                'state' => 'Hawaii',
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'http://healthandwelfare.idaho.gov/Portals/0/Medical/LicensingCertification/CNAOutOfStateTransferForm.pdf',
                'cnanote' => 'null',
                'cnaperm' => '1 Month',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 13,
                'lpnfees' => '$110',
                'lpnlink' => 'https://ibn.idaho.gov/IBNPortal/BoardAdditional.aspx?Board=IBON&BureauLinkID=100',
                'lpnnote' => 'null',
                'lpnperm' => '6-8 Weeks',
                'lpntemp' => 'NA',
                'rnfees' => '$152',
                'rnlink' => 'https://ibn.idaho.gov/IBNPortal/BoardAdditional.aspx?Board=IBON&BureauLinkID=100',
                'rnnote' => 'null',
                'rnperm' => '2-4 Weeks',
                'rntemp' => '24 Hours',
                'state' => 'Idaho',
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'cnafees' => '$25',
                'cnalink' => 'https://nurseaidetesting.com/out-of-state-cna-application/',
                'cnanote' => 'null',
                'cnaperm' => '1-3 Days',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 14,
                'lpnfees' => '$75',
                'lpnlink' => 'https://www.nursinglicensure.org/state/nursing-license-illinois.html#lpn',
                'lpnnote' => 'null',
                'lpnperm' => '2-4 Weeks',
                'lpntemp' => '3-4 Weeks',
                'rnfees' => '$50',
                'rnlink' => 'https://www.nursinglicensure.org/state/nursing-license-illinois.html#rn',
                'rnnote' => 'null',
                'rnperm' => '4-6 Weeks',
                'rntemp' => '2-4 Weeks',
                'state' => 'illinois',
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'cnafees' => '$65',
                'cnalink' => 'https://www.ivytech.edu/cna/4368.html',
                'cnanote' => 'Mail in forms',
                'cnaperm' => '4-12 Weeks',
                'cnatemp' => '2-6 Weeks',
                'created_at' => NULL,
                'id' => 15,
                'lpnfees' => '$60',
                'lpnlink' => 'https://www.in.gov/pla/2506.htm',
                'lpnnote' => 'null',
                'lpnperm' => '4-5 Weeks',
                'lpntemp' => '10-14 Days',
                'rnfees' => '$50',
                'rnlink' => 'https://www.in.gov/pla/nursing.htm',
                'rnnote' => 'null',
                'rnperm' => '2-5 Weeks',
                'rntemp' => '1-2 Weeks',
                'state' => 'Indiana',
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://dia.iowa.gov/sites/default/files/documents/2016/01/dcw_application.pdf',
                'cnanote' => 'null',
                'cnaperm' => '1-2 Weeks',
                'cnatemp' => '3-5 Days',
                'created_at' => NULL,
                'id' => 16,
                'lpnfees' => '$169',
                'lpnlink' => 'https://nursing.iowa.gov/licensure/endorsement-licensure-another-state',
                'lpnnote' => 'null',
                'lpnperm' => '5-10 Days',
                'lpntemp' => '5-10 Days',
                'rnfees' => '$169',
                'rnlink' => 'https://nursing.iowa.gov/licensure/endorsement-licensure-another-state',
                'rnnote' => 'null',
                'rnperm' => '1-2 Weeks',
                'rntemp' => '1 Week',
                'state' => 'Iowa',
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'cnafees' => '$2-',
            'cnalink' => 'https://www.kdads.ks.gov/docs/default-source/survey-certification-and-credentialing-commission/Health-Occupations-Credentialing/certificattion-(cna-hha-cma)/certification-verification/forms/interstate-application-form.pdf',
                'cnanote' => 'Must pass exam with 75%',
                'cnaperm' => 'Exam / 3-4 Weeks after',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 17,
                'lpnfees' => '$50',
                'lpnlink' => 'https://ksbn.kansas.gov/wp-content/uploads/Forms/Endorsement.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '4-6 Weeks',
                'lpntemp' => '1 Week',
                'rnfees' => '$125',
                'rnlink' => 'https://ksbn.kansas.gov/',
                'rnnote' => 'null',
                'rnperm' => '30 Days',
                'rntemp' => '7-10 Days',
                'state' => 'Kansas',
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://kbn.ky.gov/knar/Pages/reciprocity.aspx',
                'cnanote' => 'null',
                'cnaperm' => '1-2 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 18,
                'lpnfees' => '$179.75',
                'lpnlink' => 'https://kbn.ky.gov/apply/Pages/Endorsement/endorsement.aspx',
                'lpnnote' => 'null',
                'lpnperm' => '4-6 Weeks',
                'lpntemp' => '10-14 Days',
                'rnfees' => '$330',
                'rnlink' => 'https://kbn.ky.gov/Pages/default.aspx',
                'rnnote' => 'null',
                'rnperm' => '5-10 Weeks',
                'rntemp' => 'NA',
                'state' => 'Kentucky',
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'cnafees' => '$35',
                'cnalink' => 'http://ldh.la.gov/assets/medicaid/hss/NurseAide/NurseAideTrainingReciprocityForm.pdf',
                'cnanote' => 'Mail in forms',
                'cnaperm' => 'NA',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 19,
                'lpnfees' => '$175.75',
                'lpnlink' => 'http://www.lsbpne.com/requirements_for_endorsement.phtml',
                'lpnnote' => 'Temp last 12 weeks',
                'lpnperm' => '12 Weeks',
                'lpntemp' => 'Walkthrough',
                'rnfees' => '$140',
                'rnlink' => 'http://www.lsbn.state.la.us/',
                'rnnote' => 'Walkthrough with clean background. Temp cost and additional $100',
                'rnperm' => '4-6 Weeks',
                'rntemp' => '24 Hours',
                'state' => 'Louisiana',
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'cnafees' => '$20',
                'cnalink' => 'https://www.maine.gov/dhhs/dlc/cna/',
                'cnanote' => 'null',
                'cnaperm' => '4-6 Months',
                'cnatemp' => 'Can work 4 months not on registry 2 weeks',
                'created_at' => NULL,
                'id' => 20,
                'lpnfees' => '$50',
                'lpnlink' => 'http://www.maine.gov/boardofnursing/docs/LPN-Endorsement-App-10-24-16.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '1 Week',
                'lpntemp' => '7-14 Days',
                'rnfees' => '$75',
                'rnlink' => 'https://www.maine.gov/boardofnursing/',
                'rnnote' => 'null',
                'rnperm' => '2-4 Weeks',
                'rntemp' => '7-10 Days',
                'state' => 'Maine',
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'cnafees' => '$20',
                'cnalink' => 'http://www.mbon.org/Documents/cna-endorsementinfo.pdf',
                'cnanote' => 'Additional fingerprint fees',
                'cnaperm' => 'Up to 3 Months',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 21,
                'lpnfees' => '$100',
                'lpnlink' => 'https://mbon.maryland.gov/Pages/licensure-by-endorsement.aspx',
                'lpnnote' => 'null',
                'lpnperm' => '4-6 Weeks',
                'lpntemp' => 'Walkthrough',
                'rnfees' => '$100',
                'rnlink' => 'http://www.mbon.org/Pages/default.aspx',
                'rnnote' => 'Can go inside state line to expedite fingerprints',
                'rnperm' => '3-4 Weeks',
                'rntemp' => '1-2 Weeks',
                'state' => 'Maryland',
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://www.redcross.org/content/dam/redcross/atg/Northeast_Media/Eastern_Mass/Eastern_MA_-_NAT_-_NAT_Reciprocity.pdf',
                'cnanote' => 'null',
                'cnaperm' => '3 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 22,
                'lpnfees' => '$275',
                'lpnlink' => 'https://www.pcshq.com/?page=health,ulicensedpracticalnurseslpnu',
                'lpnnote' => 'null',
                'lpnperm' => '4 Weeks',
                'lpntemp' => 'NA',
                'rnfees' => '$275',
                'rnlink' => 'https://www.mass.gov/orgs/board-of-registration-in-nursing',
                'rnnote' => 'null',
                'rnperm' => '2-4 Weeks',
                'rntemp' => 'NA',
                'state' => 'Massachusetts',
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'cnafees' => 'Fees Vary',
                'cnalink' => 'https://www.prometric.com/en-us/clients/nurseaide/pages/mi.aspx',
                'cnanote' => 'Certain states require training program',
                'cnaperm' => 'Exam / 2 Weeks after',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 23,
                'lpnfees' => '$54',
                'lpnlink' => 'https://www.nursinglicensure.org/state/nursing-license-michigan.html#lpn',
                'lpnnote' => 'null',
                'lpnperm' => '6-8 Weeks',
                'lpntemp' => 'NA',
                'rnfees' => '$64',
                'rnlink' => 'https://www.michigan.gov/healthlicense',
                'rnnote' => 'null',
                'rnperm' => '4 Weeks',
                'rntemp' => '4 Weeks',
                'state' => 'Michigan',
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://www.health.state.mn.us/facilities/providers/nursingassistant/docs/interstate.pdf',
                'cnanote' => 'Must mail in',
                'cnaperm' => '2-4 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 24,
                'lpnfees' => '$115',
                'lpnlink' => 'https://mn.gov/boards/nursing/licensure/apply-for-a-license/apply-by-endorsement.jsp',
                'lpnnote' => 'Temp lasts 60 days',
                'lpnperm' => 'Varies',
                'lpntemp' => '1-5 Days',
                'rnfees' => '$105',
                'rnlink' => 'https://mn.gov/boards/nursing/',
                'rnnote' => 'null',
                'rnperm' => '4-6 Weeks',
                'rntemp' => '2-3 Weeks',
                'state' => 'Minnesota',
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'cnafees' => '$26',
                'cnalink' => 'https://www.asisvcs.com/publications/pdf/072503.pdf',
            'cnanote' => 'Must have verification of paid employment within last 24 months (ex: pay stub, w2, etc)',
                'cnaperm' => '2-4 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 25,
                'lpnfees' => 'NA',
                'lpnlink' => 'https://gateway.licensure.msbn.ms.gov/',
                'lpnnote' => 'null',
                'lpnperm' => '2-3 Weeks',
                'lpntemp' => '5 Days',
                'rnfees' => '$100',
                'rnlink' => 'https://www.msbn.ms.gov/',
                'rnnote' => 'null',
                'rnperm' => '7-10 Days',
                'rntemp' => '5 Days',
                'state' => 'Mississippi',
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'cnafees' => 'Fees Vary',
                'cnalink' => 'http://health.mo.gov/safety/cnaregistry/cna.php#challenge',
                'cnanote' => 'null',
                'cnaperm' => 'Exam / 2-3 Weeks after',
                'cnatemp' => '2-3 Weeks',
                'created_at' => NULL,
                'id' => 26,
                'lpnfees' => '$95.80',
                'lpnlink' => 'https://pr.mo.gov/boards/nursing/375-0222.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '2-3 Weeks',
                'lpntemp' => 'Walkthrough',
                'rnfees' => '$55',
                'rnlink' => 'https://www.pr.mo.gov/Default.asp',
                'rnnote' => 'null',
                'rnperm' => '3-4 Weeks',
                'rntemp' => '24 Hours',
                'state' => 'Missouri',
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'cnafees' => 'FREE',
                'cnalink' => 'https://cna.hhs.mt.gov/datamart/ePass.do',
                'cnanote' => 'null',
                'cnaperm' => '1-2 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 27,
                'lpnfees' => '$227.25',
                'lpnlink' => 'http://b.bsd.dli.mt.gov/license/bsd_boards/nur_board/pdf/nur_end_app.pdf',
                'lpnnote' => 'Fingerprint and Background Fees',
                'lpnperm' => '10 Days',
                'lpntemp' => '4-6 Weeks',
                'rnfees' => '$200',
                'rnlink' => 'http://bsd.dli.mt.gov/license',
                'rnnote' => 'Must verify all licenses held temp or expired',
                'rnperm' => '3-6 Weeks',
                'rntemp' => '2-3 Weeks',
                'state' => 'Montana',
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'cnafees' => '$20 course',
                'cnalink' => 'http://dhhs.ne.gov/licensure/Pages/Certification-and-Verification.aspx',
                'cnanote' => 'null',
                'cnaperm' => '2-4 Weeks',
                'cnatemp' => 'NA',
                'created_at' => NULL,
                'id' => 28,
                'lpnfees' => '$59.50 - $151.75',
                'lpnlink' => 'http://dhhs.ne.gov/publichealth/Licensure/Documents/EndorsementRNLPN.pdf',
                'lpnnote' => 'null',
                'lpnperm' => '2-8 Weeks',
                'lpntemp' => '3-6 Weeks',
                'rnfees' => '$125',
                'rnlink' => 'http://dhhs.ne.gov/publichealth/pages/crlNursingAppsReqsFeesLPNRN.aspx',
                'rnnote' => 'null',
                'rnperm' => '8 Weeks',
                'rntemp' => '3 Weeks',
                'state' => 'Mebraska',
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}